project:
  type: website
  output-dir: docs

website:
  title: "Documentation citoyenne"
  navbar:
    left:
      - text: Accueil
        href: index.qmd
      - text: À propos
        href: apropos.qmd
      - text: Journal
        href: hello.qmd
      - text: Notes
        menu:
          - text: Plan de cours
            href: notes/plan-de-cours.qmd
          - text: Définition évènement
            href: notes/definition-evt.qmd
          - text: Définition documentation
            href: notes/definition-docu.qmd           
          - text: Premier cours
            href: notes/cours-01.qmd
          - text: Deuxième cours
            href: notes/cours-02.qmd
          - text: Troisième cours
            href: notes/cours-03.qmd
          - text: Quatrième cours
            href: notes/cours-04.qmd
          - text: Cinquième cours
            href: notes/cours-05.qmd
          - text: Sixième cours
            href: notes/cours-06.qmd
          - text: Septième cours
            href: notes/cours-07.qmd
          - text: Huitième cours
            href: notes/cours-08.qmd    
          - text: Neuvième cours
            href: notes/cours-09.qmd                                
          - text: Lecture
            href: notes/lectures-01.qmd
          - text: Lecture
            href: notes/lecture-02.qmd
          - text: Bibliographie
            href: notes/biblio.qmd
