project:
  type: website
  output-dir: docs

website:
  title: "Documentation citoyenne"
  navbar:
    left:
      - text: Accueil
        href: index.qmd
      - text: À propos
        href: apropos.qmd
      - text: Journal
        href: hello.qmd
      - text: Notes
        menu:
          - text: Plan de cours
            href: notes/plan-de-cours.qmd
          - text: Définition évènement
            href: notes/definition-evt.qmd
          - text: Définition documentation
            href: notes/definition-docu.qmd           
          - text: Co-construction 
            href: notes/cours-01.qmd
          - text: "L’œuvre modèle : essai de genèse curatoriale"
            href: notes/cours-02.qmd
          - text: Koblowski, Témoin et expérience
            href: notes/cours-03.qmd
          - text: Ward et Payant
            href: notes/cours-04.qmd
          - text: Gümbrecht
            href: notes/cours-05.qmd
          - text: Winckelmann et Dibutades
            href: notes/cours-06.qmd
          - text: Dosse
            href: notes/cours-07.qmd
          - text: Fraser et Prioul
            href: notes/cours-08.qmd    
          - text: Caillet, L'enquête pragmatiste
            href: notes/cours-09.qmd    
          - text: Simon et Bishop
            href: notes/cours-10.qmd          
          - text: Hölling et Gusman
            href: notes/cours-11.qmd            
          - text: Documentation citoyenne
            href: notes/cours-12.qmd 
          - text: Display et bilan
            href: notes/cours-13.qmd                                                    
          - text: Lecture
            href: notes/lectures-01.qmd
          - text: Lecture
            href: notes/lecture-02.qmd
          - text: Bibliographie
            href: notes/biblio.qmd
