project:
  type: website
  output-dir: docs
format:
  html:
    toc: true
    theme: cosmo
    css: styles.css

website:
  title: "Documentation citoyenne"
  navbar:
    left:
      - text: Accueil
        href: index.qmd
      - text: Journal
        href: hello.qmd
      - text: Notes
        menu:
          - text: Plan de cours
            href: notes/plan-de-cours.qmd     
          - text: 01 - Co-construction 
            href: notes/cours-01.qmd
          - text: 02 - "L’œuvre modèle - essai de genèse curatoriale"
            href: notes/cours-02.qmd
          - text: 03 - "Koblowski - histoire orale, documentation, lacunes"
            href: notes/cours-03.qmd
          - text: 04 - "La perte - notion constitutive de l’histoire de l’art (et de l’art?)"
            href: notes/cours-04.qmd
          - text: 05 - La production de présence de Gümbrecht. Présence vs signification. 
            href: notes/cours-05.qmd
          - text: 06 - "Épiphanies et présentification - le passage par l’éphémère.""
            href: notes/cours-06.qmd
          - text: 07 - "L’événement - évolution sémantique et migration épistémologique"
            href: notes/cours-07.qmd
          - text: 08 - "L’événement sur le terrain de la performance et de l’exposition"
            href: notes/cours-08.qmd    
          - text: 09 - "Méthode - l’enquête"
            href: notes/cours-09.qmd    
          - text: 10 - La participation et la documentation
            href: notes/cours-10.qmd          
          - text: 11 - Performance (Hölling et Gusman)
            href: notes/cours-11.qmd            
          - text: 12 - Documentation citoyenne
            href: notes/cours-12.qmd 
          - text: 13 - Display et bilan
            href: notes/cours-13.qmd                                                    
          - text: Bibliographie
            href: notes/biblio.qmd
