---
title: "Bibliographie augmentée"
date : 2025-06-17
format:
  html:
    page-layout: article
    
---

Bishop, Claire. 2012. Artificial Hells: Participatory Art and the Politics of Spectatorship. London ; New York: Verso Books.

Bishop, Claire, et Dan Perjovschi. 2014. Radical Museology or, « What’s Contemporary » in Museums of Contemporary Art? 2., rev. Ed. London: Koenig Books.

Boucher, Mélanie, Marie Fraser, et Johanne Lamoureux. 2023a. « Penser l’actualité des collections: Une introduction ». In Réinventer la collection: L’art et le musée au temps de l’événementiel, 1ʳᵉ éd. Presses de l’Université du Québec. https://doi.org/10.2307/j.ctv37wpr8d.

———, éd. 2023b. Réinventer la collection: L’art et le musée au temps de l’événementiel. 1ʳᵉ éd. Presses de l’Université du Québec. https://doi.org/10.2307/j.ctv37wpr8d.

Caillet, Aline. 2019. « Enquête et démocratie : Le modèle pragmatique ». In L’art de l’enquête: savoirs pratiques et sciences sociales, 57‑76. Art, esthétique, philosophie, n. 6. Milan] [Paris: Éditions Mimésis.

Davis, Whitney. 2013. Gay and Lesbian Studies in Art History. 0 éd. Routledge. https://doi.org/10.4324/9781315876825.

Dosse, François. 2010. Renaissance de l’événement: un défi pour l’historien, entre sphinx et phénix. Le noeud gordien. Paris: Presses universitaires de France.

Fraser, Marie. 2023. « La muséologie évènementielle ou la résilience des collections ». In Réinventer la collection: L’art et le musée au temps de l’événementiel, 1ʳᵉ éd. 
Presses de l’Université du Québec. https://doi.org/10.2307/j.ctv37wpr8d.

Ginzburg, Carlo. 1980. « Signes, traces, pistes: Racines d’un paradigme de l’indice ». Le Débat n° 6 (6): 3‑44. https://doi.org/10.3917/deba.006.0003.

Greenberg, Reesa. 1997. « The Exhibition as Discursive Event ». In Longing and Belonging : From the Faraway Nearby, 118‑25. Etats-Unis: Site Santa Fe. https://www.yorku.ca/
reerden/Publications/EXHIBITION/exhibition_discursive_event.html.

Gumbrecht, Hans Ulrich. 2009a. Éloge de la présence: ce qui échappe à la signification. Traduit par Françoise Jaouën. Paris: Libella-Maren Sell éd.

———. 2009b. « Épiphanie/Présentification/Dexis : Avenirs Des Humanités et Des Arts ». In Éloge de La Présence: Ce Qui Échappe à La Signification, traduit par Françoise 
Jaouën. Paris: Libella-Maren Sell éd.

Gusman, Tancredi. 2023. « Introduction : On the Present of Past Performance. Investigating the Practices of Reconstructing and Representing Performance Art ». In Reconstructing Performance Art: Practices of Historicisation, Documentation and Representation. Routledge Advances in Theatre & Performance Studies. London: Routledge. https://www.taylorfrancis.com/books/9781003275909.

Hennion, Antoine, et Bruno Latour. 1996. « L’art, l’aura et la distance selon Benjamin ou comment devenir célèbre en faisant tant d’erreurs à la fois... » Cahiers de Médiologie, nᵒ 1, 234‑41.

Jones, Amelia. 1997. « “Presence”in Absentia: Experiencing Performance as Documentation ». Art Journal 56 (4): 11‑18. https://doi.org/10.1080/00043249.1997.10791844.

Kolbowski, Silvia. 2016. an inadequate history of conceptual art Catalogue of installation. Paris: INHA - Institut national d’histoire de l’art.

Lecercle, Jean-Jacques. 2005. « Il y a événement et événement ». Polysèmes. Revue d’études intertextuelles et intermédiales, nᵒ 7 (janvier), 249‑64. https://doi.org/10.4000/polysemes.1687.

Payant, René. 1987. « Notes Sur La Performance ». In Vedute : Pièces Détachées Sur l’art 1976-1987, 293‑300. Laval, Québec: Trois.

Rancière, Jacques. 2008. Le spectateur émancipé. Paris: la Fabrique éd.

Simon, Nina. 2010. The Participatory Museum. Santa Cruz: Museum 2.0.

Ward, Martha. 1996. « WHAT’S IMPORTANT ABOUT THE HISTORY OF MODERN ART EXHIBITIONS? » In Thinking about Exhibitions, édité par Reesa Greenberg, Bruce W. Ferguson, et Sandy 
Nairne. London: Routledge.
