---
title: "Documentation citoyenne"
date : 2025-06-12
format:
  html:
    page-layout: article
    
---


Comprendre la muséologie citoyenne pour faire de la documentation citoyenne. 

JL s'appuie sur les entrevues faites dans le cadre du CIECO. 

Museo cioyenne, modalite de la museolo participce, ambitionne de transformer ou en tout cas postule la possible transformation de l'instittuion, les acteurices humaines et la societe ou tout ce beau monde se rencontre. 

Comment articuler le pariticpa et le citoyen ? 
Poser la quesiton du seuil entre les deux ? notamment le seuil du transformationnel. 

Prendre en considération : 
- Prevalence du DIY 
clair que il y a une double du paradigme participatif ; 
celebration comme chez Simon, mais aussi un element de culture quil faut mettre en collab avec le neoliberalisme. 

notamment dans le mesure ou une des manière de participer : participer dans le cadre des entreprises : sollicitant de la participation des usagers, phenomene surtout avec l'IA. 

Consommation culturelle : appetit de chacun pour les likes, les commentaires et les partages sur les RS. Mais aussi avec le karaoke. Les menu telephonique. 
Vrai aussi dans la consommation marchande : Caisse éléctronique. 

Entrevoir une vie quotdienne, ou on aura quasiment plus d'echanges de la vie ordinaire. 

participatif ==> rentabiliser davantage avec des nuances dans la conso culturelle de donner l'impression aux gens qu'ils en font partie. 

remarque de JL : reduction des echanges, on la retrouver aussi dans les diagrammes de Nina Simone

Malgré les eloges du participatif de Simon, aucun lien entre les participants. Simplement un Bottom to top qui s'ajoutait à un top to bottom. 
reciprocite entre les individus et l'institution. 

Ce paradigme n'est pas innocent dans ce qu'est deveni le participatif. 

Impasse du participatif, ex de Cadichon : La memoire d'un anne de la comptesse de Segur. 

argument de la démocratisation, c'est pour tout le monde pareil. 


Valoriser faire de l'art plutot que de l'histoire de l'art. 
On s'étonne des outrances du je sur les reseaux sociaux mais provient d'une longue praitque de l'hypetrophie de l'expression. 

Par ailleurs, mediaiton on fav dans les exercices de creation, les ateliers. Favoriser une strategie mimetique. MAJ, "À jouer"
On vous fait rejouer pour comprendre. Visite d'expo puis vont en salle faire à partir de ce qu'iels ont vu. 

ateliers du MAC, les enfants (souvent) se sont expliquer les contraintes à respecter : art contemprain c pas du n'importe quoi, repond a une serie de contraintes. On encourage pas les gens à libre expresison. 
On les inscrit dans une strategie mimétique. Si on le prend a une echelle plus large c'est ideal pour conforter à l'individualisme de la grande ehelle sociale. 

defait completement le regime esthetique tel qu'on a la connu depuis 200 ans, d'une théorie de l'art vue comme la capacite des artistes à transgresser les regles, reformuler l'horizon d'attente, à ne pas se conformer !

- giotto fin XVIIIe : paradigme mimetique, mode imiation est la regle principale 
- mi XVIIIe : apres avec Diderot notamment, idee que l'esquisse est plus importante, inspiration doit se laisser sentir. 

Labarthe et Nancy  : paradigme de l'expression et plus de l'imiation 

- ensuite 1945, Anne Coquelin annonce que l'art contmeporain est regime de la communicaiton 

théorie de l'art comme modifications des règles, qqch d'important surtout avec le paradigme de l'expression. 

- Impasse Cadichon pour JL : passion pour la comtesse de Ségure. Fascinée par la description. Absence de referent rendait magique la description. 
- choc en lisant les memoires d'un âne. 
A du mal à s'expliquer pourquoi cette passion nait car à la télé animaux parlaient déjà mais l'âne ne parlait pas seulement car il écrit. Intervention constamment dans la narration 

Tentative d'ecrire les Memoires du chat par JL : Memoires de Mooki. Ça ne fonctionnait pas, commprend alors l'idée que de toute facon, pas possible. 

JL se rend compte que les mémoires de mooki étaient les memes choses que les memoires de l'âne. L'originalité n'etait pas dans l'ecritutre mais dan sle concept. Pour faire quelque chose d'original il fallait qu'elle change les règles. 

Idée est de reprendre, broder differennt. Pas un art de l'inventation, mais presque un art de la paraphrase. Les regles changent avec la modernité. 

Meilleurs artistes sont ceux qui n'ont pas de following. Ceux qui terminent leur mode. Ex : pollock

perf de JIM DINE : Walking Memory, 1959-1969. vue comme un des premiers happening. 
Il boit la peinture à meme le seau. 
Il se revendiquait de Pollock qui était mort 

Photo de Pollock de Hans Hammouck publiées dans LIFE. https://www.phillips.com/detail/hans-namuth/NY040317/35?preview=1 Artiste connu par ces images plus que par ses peintures. Pollock, I am in the painting. C'est ca que Dine essaye de renverser. I am the painting. 

Esthetique de la reception. Happening de Dine peut etre interepreté comme un jugement et reponse suit la proposition esthetique de polock dans ce qu'elle a d'irreproductible. 

Impasse Cadichon : idée que tout le monde va faire pareil, et que tout le monde va apprécier l'art en en faisant. 

Nous donner à penser à quel point le concept de participaiton s'est renversée entre le debut des années 1960 et aujourd'hui. 

Perf de Max Dean, postulait qu'il fallait cassé l'inertie des spectteurs. S'inscrivait dans l'abolition frontiere entre oeuvre et publique. 

oscillation entre oeuvre et public. vraiement qqch qu'une frontiere avait été abolie. 

C'etait bon parce que Debord avait critiqué la passivité du spectateur. 

spectateur = bad, participant = good

Bcp d'intervention de perf avait pour but l'

emancipation suppose de la societe du spectateur. Basculer d'un canal sensoriel, scopique de la vue à l'oral 

jusque qu'il fasse du bruit dans la perf de Dean. 

Typique de la demonition du regard == Philo francaise : [Martin Jay Downcast Eyes ](https://archive.org/details/downcasteyesdeni0000jaym)
Le regard a mauvais reputation. 

Debord etait persuadé qu'il faillait émanciper de la position de spectateur. 

Depuis, il y a eu des critiques de Debord, la societé du spectacle et notamment dans l'œuvre de Rancière dans le [spectateur émancipé](https://www.babelio.com/livres/Ranciere-Le-spectateur-emancipe/175483) : il y a du spe emancipé. 

emancipation commence quand on remet en question l'opposition entre regarder et agir.

si on regarde, on fait rien. 

Exemple Théatre Brechtien

quand on comprend que les évidences qui structurent ainsi les rapports du dire, du voir et du faire, appartiennent elles meme a la strucuture de la domination et de la suggestion

Postition entre regarder et agir c'est penser le monde enterme de structure : dominant, assujetis. Il y a les dominés les dominants. 

emancipation du spectateur c'est alors l'affirmation de sa capacité de voir ce qu'il voit et savoir quoi en penser et de savoir quoi en faire. 

Au fond, il accuse Debord de paternalisme. Comme si on ne pouvait pas leur faire confiance. 
Ranciere, aussi auteur le maitre ignorant. 

"être spectateur doit être penser comme un tache active, cad une action qui engage le spectateur dans la responsaiblité que sous-tend le fait de regarder."

Quand on sait tout ça, on ne peut pas proceder à l'espece de vision salutaire de la participation comme le defend Nina Simone. Sentiment parrfois que les activites qu'elles proposent une therapie occupationnelle. 

Passage d'un article d'Emilie Oussa dans Spirales. 
exemple image pensive Ranciere, image qui fait pensee et qui propose une troisieme jeune fille amoureuse : Origine de la peintire, celle de Winckelmann
Nous parle d'une discussin 4nov 2002 sur les écrans citoyens. 

Godard avait donner comme exemple une jeune fille quoi voit l'image de l'homme qu'elle aime au bras d'uen autre. Elle voit ce que nulle autre ne peut voir. Montre bien la possibilite de penser qu'il existe dans l'immediatté de voir.  

Ne peut exister que pour elle. Dans l'imediatité du voir. 

Oussa continue, une image n'est pas sensé pensée elle est 

seulement objet de penser. Une image pensive c'est une image qui recèle de la pensee non pensée. 

Pas assigniable à celui qui la produit et qui fait effet sur celui qui la voit sans qui la lit a un objet determiné. 

Mise en garde JL ==> Objectif : ne jamais conferee au partiicpatif une valeur absolue. 

ce qui est dangeurx c'Est de lui conféré la valeur absolue au sens ethymo de absolu. 

detache de tout, auc ontraire il faut le penser dans la contingence et l'efficace. Ou, comment et a quel fin ? 

Ici, on rencontre le citoyen. 

Si terme participation a fait un flip ces 50 denieres années, il est arrivé la meme chose du terme citoyen. 

complication polysémique, aussi un terme qui a été retourné sur la tête. Terme qui se veut inclusif 

musee citoyen, on est persuadee que c un musee qui se veut inclusif, pour tous·tes. Il est d'abord égalitarisme

devenu un terme d'exclusion. Histoire du suffrage qu'on va appeler universel etait avant l'histoire d'un statut privilegee male et proprio qui operait dans un monde ou citoyen etait un titre, un privilege. 

Activites citoyennes dans les musees : On l'attend au sens de la revolution. 

Etre citoyen c'est avoir les bons papiers. 

appartenance située (rapport de lieu, de proxmite) qui se heurte a une revendication d'un fantasme universel. Rien de plus oxymorique de penser que la citoyenneté est universel. 

Ici au Québec, le terme citoyen n'a pas le même sens. 

être un citoyen : different que d'être un participant. 
Participant est qqch qui participe
citoyenn pourrait être citoyen, doit détenir certaines titres : une preuve d'adresse, un passeport. Concept de sans-paiers dit bien que tout le monde n'est pas citoyen. 

L'embleme du citoyen cest le sans papier. etre citoyen ne tient pas a ce que l'on fait mais a ce que l'on est. 

citoyen du monde : oxymore

## Muséal Montréalais


On utilise pas universelement mais à Montreal : deux musees qui ont en fait un evenement : 
- Ecomusee du Fier Monde en 2011
- Musée McCord en 2016

Les deux s'apparentent a des logiques complètement différentes. 

### Ecomusee 

salon privée depuis le debut des années 80 devenu musee a la fin des années 90. 
fonctionnait dans la foulée

Table de ronde de Santiago en 76

nouvelle museo qui va accompagné la creation des eco musée. 
ecomusee = musee de milieu 

Musees sont rpesques des franchises, en France. Ils ont ocmme musee celui de Mtl. 
Fier monde est un modele du genre. 
Au quebec ont presque tous disparus. 

S'adresse au quartier. Ouvert aux organismes communautaires du quartier, passé industriel, reattribution par les gays. 
mais on aussi un patrimoine industriel important dans leur collecitons, qui valorisent bcp. 
Survivant de cette generation del l'eco musee et enjeux de proximitée qui etaient à l'œuvre dans le concept d'ecomusee. 
Ont des collections, redirige des donations, ont plus d'interet pour collectionné patri indus, docu des orga, qu'archives personnelles. Interet pas sur le materiel mais sur l'immateriel 

Statut de musée agrée. Mais ne se considere pas comme reference museal ou de connaissance technique. N'ont pas de conservateurs. 
Un musee où la co-création a une place centrale. 

Beaucoup d'initiatives sociales (analphabetisation), raconte l'histoire du quartier (expo sur les cuisines)

vie politique se faisait dans les cuisines. Appartement montrealais typique. Grand coridor avec chambres de chaque coté et cuisine a la fin de l'appartement. La cuisine devient le lieu de rencontre. 

Il faut qu'un organisme communautaire est envie de porter de tels projets. Tres svt les orga communautaire viennent pour les anniversaires mais l'eco musée depasse juste le sujet anniversaire pour mettre en valeur plus que ça. 

comment le mouvement citoyen fait avancer les choses. Interet pour le citoyen comme mouvement citoyen, pas en tant que somme d'individus citoyenes. 


### McCord

musee d'histoire sociale

centrer sur la metropole montrealaise. 

À l'origine musee universitaire de McGill avec collection problematique. Professeurs revenaient avec des "souvenirs" de leurs voyages. Provenances douteuses. Ils ont encore des objets dont ils ne connaissent pas la provenance. 

Ont des restes humains. Redpath en ont aussi, vont faire une salle du souvenir, cimetiere, salle de repos pour reflexion sur le musée. 

3 axes prio de collectionnement 
- Photographie, Notman 
- Textiles (mode mais tissus)
- Artefacts autochtones

Mandat de la ville de Mtl :  rapport de proximité 
plus ambitieux pour garder une des plus grandes collection sur l'hist de Montreal on reçu la collecton de lhopital Juif ont donné 50000$ avec condition que cette collecton dne sorte jamais de MTL. 

McCord, c'est le Carnavalet. Mais on dirait de Carnavalet que c un musee citoyen. 

Entretien avec ancienne directrice, Suzanne Sauvage : produire musée engagé dans la decolonisation, tournant critique et social. Voulait que le musée produise des expo critiques. si l'objet presente des problemes : vous l'écrivez sur le cartel. 

Suzanne Sauvage est du monde des communications de base, et non du monde des musées. 

Retrouve la genealogie de l'utilisation de ces idées dans les autres musées en suivant le parcours des personnes.

Les musées de ville (city museum), pas du tout en tradition francais, mais anglophone, neearlandais et allemande. 

Plan strategie de 2016 : s'est déclaré musée citoyen et ....

justification par le fait que citoyen et l'adjectif de cité. Mais le programme que SS donnait au McCord 

co-creation au centre du programme ainsi que la decolonisation du musée. 

SS va faire une année de formation : inviter des gens des city museums et de la decolonisation. 
qu'est ce que c'est decoloniser les collections ? Toujours en cours

Abandon du top to bottom. Musée donne des outils mais laisse le public décider et remonter les infos. 

Ecomusee est trop petit pour faire un tel exercice. McCord s'est mis a penser la **transversalité** puis à mandater des gens de la mediaiton : pour faire un projet d'équipe inter ou personne de difft dept travaille sur un meme projet. 

D'habitude, journée pitch des expositions à venir. Alors que projets sont créés par tous. Tranversalité plutot que silotage. 

Beaucoup de directeur ont mené le travail en tant que chef d'orchestre, en diva et pour ça pour que dans un musee ce travail fonctionne, il faut que son travail soit le travail de tous. 
Alors que la transversalité est plus horizontale. 

### Autres musées

Ecomusee et City museum ==> deux origines differentes, mais des pratiques communes fondées sur le co-creation. 

Ecomusée du fier onde en retard ur l'edi puisque attention sur l'ouvrier. 

Designations plus souples : ou il n'y a pas eu pas de rebranding institutionnel. Etiquette peut etre inspiré de differentes sources.  

2011 : EcoMusee se declare comme un musee citoyen, "coming-out du musee" on est content que le musée le fasse mais on est pas étonné. 
Cette revelation n'est pas moteur de transformation. 

A côté de ca, autre usage du terme citoyen au MNBAQ. Il a remplacé la designation des publics par des citoyens. Mais s'accompagne pas forcement de politiques citoyennes. 
Musée d'Etat  donc utilise le bon terme de citoyen. 

Le MEM embauche boite locale : com par la boite rouge, expo urbania. 

Sortir de son musée, et aller dans les communautés. 

Sortir des questions de rentabilité 

### Impacts Pratiques

Comment impactent-elles les pratiques ? 
 

Sur quels terrains de l'institution se passent ces nouvelles pratiques? Quetion importante pour determiner notre terrain de recherche. Pasle prob de trace et de documentation mais delimité ce qui doit etre documenté .

Terrain de la programmation 
Prédominence de la co-creation chez les musees qui ont des velihités citoyennes. 

Dans les musees en general, des que questions importante on va s'associer à un partenaire qui a une expertise. 
difference avec la collaboraiton. pas un mandant qui est donné en amont et les choses sont prédeterminées. 

#### Terrain de la médiation 
- difficile a determiner, comment on fixe le seuil de la transformationnalité

#### Terrain de l'action culturelle 

Pour les musees qui ont des pratiques qui semblent assez conservateurs dans leurs pratiques DEI, quo inclure des evenements qui sollicitent de multiples intervenants culturels. 

Musique du monde par exemple. Est ce que c'Est citoyen ? 

#### Terrain de la gouvernance

Action pour inclure citoyen au comité de la gouv, des acquisitions. 

comite des acquisitions 

Choix des citoyens dans groupes marginalisés. Difficile de faire de recrutement. 

ZR : comment on va des annonces de recrutement dans les groupes marginalisés ? 
On peut parler de sa volonté mais ne pas afficher vulgairement des politique EDI mais parce que ça commence à être insultant pour les "gens visés". 
Pas seulement diversité de couleur ou de pensée autour de la table. 

Pour les résidences de chercheur·euses en recherche-création du parteneriat CIECO : recherche de candidats qui avaient de réflexions et d'expériences sur la décolonisation du musée. 

Diversité dans les comités est un rappel de sortir de l'entre-nous, particulierement au comité d'acquisition des oeuvres. 

## En attendant les chantiers 

Titre inspiré des Chantiers WIki au MNBAQ. Atelier Wiki du MNBAQ : 4000 fiches par les citoyens collaboration. Contribution participatives 

Documentations dans ces terrains? 

Pas de suivi de l'experience citoyenne. 

Comité secret et pas un gros suivi documentaire contrairement aux chantiers assez bien documentés
Ecrit pour interpeller les gens. Nathalie Thibault. 


## Programmation et Mediation sont problematiques pour le documentation citoyenne. 

Une des difficulté de delimité lieux de la docu citoyenne, pas seulement les seuils, c'est que contraitement a la documentaiton d'une expo ou d'une forme artistique, on documente un terrain qui n'est pas prealablement delimitée. 

Travailler sur un objet l'expo, definir si une expo, le medium expo...

Définir le terme citoyen en premier lieu, pas prealablement construit pour dire qu'on balise la documentation et les traces possibles de ces pratiques là. 

Ce qui esr caracterise la programmation citoyenne, c la co-création, Mais elle est un obstacle à la documentation. 

Intervention JL sur la mediation phatique. 
3 raisons :  
on a pas le temps
important est de le faire donc on le documente pas 
on ne peut pas imposer un modele de documentation,  alors qu'on souhaite laisser libre la co-creation

on peut avoir son propre protocole de documentation, son cadre processuel et ne pas en faire une imposition au partenaire avec lequel on travaille. On peut lui montrer, lui demander son avis ou avoir une discussion. 

Réflexion du Mccord, l'equipe mediation et action culturelle et citoyenne commence a voir comment travailler sur ca differeemnt. 

Mc cord travaillait avec prestataire est maintenant approché par orga commu. 

Reticence à tout protocole prealable de documentation, fort problement vous travailler sans objectif et sans indicateur. 

Pas forcement d'indicateur de réussite. 
Ce serait quoi ? Avoir plus de gens, que l'achalandage augmente. 

action citoyenne peut pas etre quantitative. imlique fidelisation au dela du nombre. 

sentiment d'appartenance chez des gens, qui habituellement n'en avait pas.

Un des caracteres des pratiques recurrentes des musees citoyens : programmation qui porte sur les citoyens, ils en sont le sujet. c tres classique. rend la documentation comme celle de n'importe quelle expo. 

Le MEM est un musee dont la dimension citoyenne est largement portée par des propos citoyens. Les citoyens sotn sujets, eventail de paroles et de sujets, avec une obsession de la representation. "Une personne de chaque"

Valorisation de l'oralité. Musée ont idee que mediation et oral mais aussi Une des raisons pour lequelles la question citouenne est aussi mal documentée dans les musées. 

Museologie citoyenne = regime de l'oralite, quasi systematique. 

Comment on determine, si on distingue le citoyen du participatif, par son objectif transformationnel. Quel est cet objectif transformationel ? 

Mimetisme, je me reconnais = ma parole est reconnue. 

---> tous les musées devraient ils etre citoyens ? Fier onde L

les expos citoyennes sont citoyennes au nv de la thematique. JL est pas sur du seuil de l'objectif transformationnel. 
Transformation à quel nv? 

Pas thematique, c'est un fonctionnement d'être citoyen. Un musee citoyen est-il pour les citoyens ou agit comme un citoyen ? Les musees disent les 2. Urgence d'agir en citoyen, c'est l'urgence ecologique. 

Fier Monde : EDI ne les interesse pas 

Un autre musee quo s'en soucis pas : Pointe-a-Cailliere 
fonctionne, semble-t-il, dans un regime d'autarcie. 

politique gouvernementale canadienne pose DEI comme fondamentale. Quebec demande que musee doivent etre imperativement ouvert a tous. 

MEM avait fait distinction dans ce qu'est etre citoyens. 

Autre volet d'activite, "Kiosque", sous-traitance de leurs espaces par communauté qui viennent présenter leurs projets. 

Hosting, 4eme categorie de Nina Simon. 

Obsession aussi pour la question de l'oralité, bcp d'archives orales au MEM. 

**Est-ce-que la documentation citoyenne va revnvoyer a ce qu'on produit pour les citoyens (expo themathique, les kioskes etc)ou si c une documentation de la reponse citoyenne de ce qui est produit pour eux ? ** 

SPOILER : les musees le font pas du tout. 

Kiosques, on en trouve aussi ailleurs sous une forme un peu differente. 

JL approchée au debut de la chaire par la biosphere et le jardin botanique : La maison de l'arbre.
Espace citoyen ouvert a des projets : Montrer que cela n'a pas de bon sens. 
Produit des initative tres ludiques, exclus en creant d'un silo citoyen mais la question citoyenne est reelle quand elle investit le musée. 
Est-ce-que c'est un pouvoir transformationnel ? 

Archives les comptes-rendus de médiateur·rices apres chaque visite. 

Rapports de mediateur sont documentation citoyenne. 
Il faut en lire bcp pour trouver des chsoes intéressentes. Pas de protocoles ou des formulaires à cet effet. Pas d'objectifs definis, pas de reflexions processuels. 
Observe quantitatif ou simplement la qualité du groupe. 

La biosphere n'est pas la seule a le faire, aussi le MBAM (?). Rapports sont meme numérisés. 

Biospohere : comprhension que les mediateur·rices pourraient joue run rôle clef. Mais formation donnée a ces médiateurs, toujours un transfert de connaissance. Il faut deplacer vers l'interrogatif. 

--> dire au groupe que ca fait parti d'un tournant reflexif du musée. J'étais la. 
utiliser les usagers : remuneration. 

Epiphanie sur l'expo immersive sur le plastique. 

Salle de data, de partage de données
plus scientifique. Aurait pu etre plus citoyen. Le public y passait beaucoup plus de temps. 


Comment on pourrait travailler la mediation dans une pratique réflexive et critique pour moissonner cette reponse citoyenne ? 

reponse des citoyens : peut etre sous forme de commentaires dans le livre d'honneur, reponse de citoyenne de creation (atelier mais aussi dans les oeuvres), exercice de reflexion sur les musées (cartels) 


produit par les citoyennes et non pas pour. 

ce qui interesse CIECO dans la difficulte ce qui est produit, est documenter par les citoyens. Donner sens au traces lacunaires (reponse des citoyens : commentaires dans le livre d'honneur ect) 


Presque sans contexte, seulemnet aurelé de leur statut de trace citoyenne. Musee en font pas mal dans leur projets ex-situ. 
Expériences hors musees, aller à la recontre de. 
Cheffe de media au mac, on a recruté un specialiste de co-creation en mediation. Approche centre communautaire, leur trouve un theme et ils font un atelier ou font la creation. chaque semaine le musee va au centre. Therapie occupationnelle. 

Action communautaire comme branding. Ils ont fait un film, la dessus. Ca c'est documenté. 

--> frac hopitaux, bourse artistes drac. Pas label citoyen en france sur des initiatives. 

Au Québec, ce serait considér comme des initiatives citoyennes. 
si c'est le musée qui les intie. 

#### Solution épistémologique

Il serait interessant de détailler l'hypothèse epistémologique. 

Le musée d'art se pose comme musée de la culture. 

Au Québec, tous les musees scientifiques on été reinvintees. Mot "science" a été substituée pour des espaces de vie. 
Mots enlever des sites meme pas seulement des titres. 

Comment les cadres referentiels des musées ont été révisé : 

Les musees d'histoires sont des musees citoyens, sciences par vie, art remplacé par la culture. Mais en réalité, la tradition scientifique, esthetique, pratiques historique ?

Participation citoyenne dans les sciences est intrinsèque a la science participative ?? Contribution citoyenne qu'on a tendance a negligé dans les etudes citoyenne parce que petites mains qui produisent du quantitatif de maniere anonymes. 

Les musees scientifiques favorisent les sciences participativess comme implication citoyenne, les beaux-arts sont obnibulés par l'art theratipie ect qui remet l'experience individuelle au centre. 
Les musees d'histoires sont en prise avec le communautaire. 

L'ecocomusee du Fier Monde pour résoudre l'absurdite de garder tous les travaux qui sont produits en ateliers : a toujours fav en lien avec ces expos, les productions collectives, qui ne sont pas amonymes, mais collectives. Par exemple, c'est tel groupe ect. 


MBAC. Usage de la production des ateliers, demagogique 


### Conclusion 

Sortir de l'impasse passe par la formalisation d'un processus.Parce que si on veut docu des activités citoyennes,il va fallor documenter ce qui a eu lieu des photos diffusables de l'activité, pour l'instant obligé de flouter les images. 

mais pas seulement, aussi produire et documenter tout ce qui a rendu possible d ece qui a eu lieu 

Les appels de participation, la liste des participations, les étapes et objectifs, ententes, autorités. Bilan avec l'avis du partenaire. Coproduction de savoir sur les collections. 

Les étapes c'est extrement important. On ne peut pas impliquer les publics, si tout le monde n'a pas un sens clair ce qui de l'objectif. 

Indicateurs de reussites doivent etre formulés en fonction des objectifs

Indexation des complémentaires des collections, production du discours sur l'œuvre. Ou les mettre ces données ? Une note de la base de données?

Encourager la paroles autour des activités afin d'avoir un processus mieux defini qui va generer piste docu pour chacune des espaces. 

Refaire le tour des notions : lund i 