---
title: Introduction
date : 2025-05-08


---

## plan du séminaire

### Bloc 1 : la présence et la question du deuil de la plénitude

#### Mardi 13 mai

- Après Kolbowski, question de l'absence et son rôle dans l'histoire de l'art (HDA) en tant que discipline.
- Objets dans le paradigme de l'HDA : l'histoire n'a pas un axe où les traces matérielles et la présence de la matière jouent un rôle aussi  important.

#### Jeudi 15 mai

- Textes premiers sur nos projets :
  - Notes sur la performance de René Payant.
  - Martha Ward, "What's is History of ?"
  - Comment faire l'HDA de l'exposition, manière d'empêcher ou de contrecarrer leur éphémérité.
  - Peu intéressé par la documentation.
  - Trouver des topoi, des lieux communs pour parler de l'exposition.

#### 20 mai : Présence

- Plénitude et Présence, Gombrech.
- Parallèlement à la montée en puissance de ces nouveaux objets, échapper à la tyrannie de la signification.
- Exposition : valorisation de l'objet par son potentiel symbolique, discursif.
- Voir texte sur Winckelmann de Whitney Davis. Intérêt à l'époque pour une jeune fille enlevée par son amant. Winckelmann parle de son rapport à l'art de la même manière. Ne plus voir que les ruines pour parler de  l'objet qui s'en va à l'horizon.

#### 22 mai

- Pensée par cas.

### Deuxième bloc : 27 mai - 17 juin (pas de cours le 19)

- Archives : expédition pour le 19.
- Collection orpheline, Musée McCord : absence de provenance.
- Musée national des beaux-arts du Québec : conférence de Clémentine Deliss.
  - 5000 œuvres orphelines.
  - Le musée métabolique de Deliss : l'importance des tableaux de seconde zone et ce qu'on peut en apprendre.
  - Apprendre des "croûtes".
  - Champ de la muséologie très présent en livre numérique.
  - Inviter Clémentine Deliss pour un workshop ?

## Cours  

### Art contemporain : modèle de l'exposition et de la réflexion Snow et Kolbowski

- Génétique curatoriale : une documentation absente.
- Exposition contrairement au texte ou aux œuvres : comprendre comment l'artiste en est arrivé là. Le commissaire prend pour acquis que ce qui est important est ce qui est mis à vue.
- Le conservateur : s'explique par la tradition française et dans les  musées d'État ici, devoir de réserve. Imprégné très tôt dans son  apprentissage de ce devoir.
- Un agent public est soumis à diverses obligations : devoirs de  réserve et de neutralité, obligation de discrétion professionnelle et,  dans certains cas, secret professionnel.
- Le conservateur n'est pas aiguillé pour revendiquer ses idées et  pour produire sa pensée propre, inverse dans le champ universitaire.
- Beaucoup de cette littérature est conflictuelle et le produit de  l'expo doit toujours apparaître comme ayant surmonté cette épreuve et  s'inscrit dans la logique irénique du musée.
- Difficile de porter les informations en dehors du cas, souvent des résistances individuelles.
- Fred Wilson : "Undermining the Museum". Pièce de critique  institutionnelle mais aujourd'hui en parle comme une épreuve  thérapeutique.
- Beaucoup de musées ont fini par se sentir coupables mais cela ne  rendait pas créatif. Alors que sortir une critique permet de traiter  cette histoire du musée problématique.
- Pourquoi ne parle-t-on pas des problèmes ? Aucune trace des problèmes.
- Matériel dangereux car proche du potinage. Souvent nominatif.
- Rester du côté fonctionnel si on veut des résultats.

### Chronologie des événements et expositions

- 2003-2007 : Période de réflexion et de développement de projets.

- 31 octobre 2003 : Début de l'exposition Carr, tournée jusqu'en 2008.

- Automne 2003 : "Doublure" - Intérêt du vêtement comme vecteur relationnel et social.

- 31 octobre : Think tank autour d'Emily Carr. Tout le monde autour de la table a écrit sur l'artiste sauf JL qui avait seulement écrit un  article sur l'artiste comme porteuse d'altérité.

- Vancouver Gallery : veulent faire une grande expo Emily Carr.  Doivent s'associer à un musée mais le musée du Canada a déjà fait une  expo sur l'artiste. Ne savent pas quoi faire de plus. L'expo de 1990  avait eu un échec cuisant.

- Comment pourrait-on encore exposer Carr sans susciter la fureur du monde de l'art ?

- La bonne femme qu'est Emily Carr : contemporaine de Proust,  formation académique à San Francisco puis Londres. Internée puis décide  de voyager au Canada.

- Elle voyage beaucoup au Canada, Nord du BC, visite des "villages  indiens", volonté de "commémoration" de cette culture qui est en train  de disparaître en documentant les villages, vies, œuvres autochtones.

- Elle est découragée car elle n'a pas les compétences techniques.  Pour elle, elle doit maîtriser de la nouvelle modernité. Elle voyage  solo en France au début du XXe siècle.

- Fait des ateliers pour s'approprier les différents langages. 1911 : Pour rendre justice aux cultures autochtones.

- 1913 : elle fait une expo avec une centaine de ses œuvres sur la  culture BC. Aucun achat car la modernité n'est pas un langage acceptable pour la bureaucratie, pas le bon style pour documenter. Ex: *Arbre, France* 1911.

- Années 1920 : C'est la merde pour elle parce que personne ne veut de ses croûtes.

- Elle se met donc à faire de l'artisanat "autochtone". Elle s'est  beaucoup fait accuser de ça. Dit elle-même avoir prostitué les savoirs  autochtones. Ce qui rend difficile ces expositions actuellement.

- A pratiquement abandonné la peinture pour l'artisanat.

- *Autoportraits*, 1925.

- Elle est découverte : exposition : Canadian West Coast Art. Native and Modern. 1927.

- Années de grandes répressions : Eric Brown, directeur de la galerie  et on lui rapporte d'exposer que l'école des 7 (que des mecs blancs of  course).

- Idée d'identité nationale ? On l'accuse de centralisme. Il consulte  Barbot pour exposer d'autres gens, c'est là que Carr est incluse dans  l'exposition. Et elle devient une figure renommée et elle se remet à la  peinture.

- Elle repart en expédition.

- *Strangled by Growth*, 1931.

- Proche d'Harris qui lui dit d'arrêter de copier mais trouver son style.

- *Détroit Juan de Fuca*, 1933-1936.

- Elle arrête de peindre vers 1936 pour des raisons de santé, et se consacre à l'écriture.

- Devenue sujet controversé au Canada.

- Retour au Think Tank : Elle est reconnue rapidement, beaucoup d'expos sur elle. A été exposée à la Documenta.

- Bref, on fait une expo sur quoi ? Montrer comment vous l'avez créée : "le monstre canadien".

- Les grands moments de sa mise à vue au Canada.

- JL propose de refaire chrono des scénographies.

  - Refaire l'exposition de 1927. Art Gallery of Ontario.
  - Volonté d'expliquer le projet colonial, et comment cela la mise au  monde de l'artiste. Comment c'est devenue un monument et un symbole de  l'Ouest Canadien.
  - Au lieu d'être centralisé en termes de lieux clés aux US en tant que scènes artistiques : dénominateurs communs : Canada, c'est vraiment  plus des spécificités géographiques.
  - Figure de l'ouest.
  - Ensuite montré comment exposé pendant le règne du cube blanc, comme Doris Shadbolt au Musée des beaux-arts du Canada en 1990.
  - L'expo se déroule pendant la Crise d'Oka en 1990. Aucune  reconnaissance de l'appropriation de la culture autochtone. Discours  formalistes ne sont pas encore dans les musées.
  - Rétrospective à son décès : 1945, commissaire : Lawren Harris. Première rétrospective à sa mort.

- Donc JL fait cette proposition : devoir refaire une expo  essentiellement colonialiste et liée au désir d'appropriation des  traditions autochtones. Se rendait pas bien compte, 2 mois après la  proposition, Hill confirme la proposition. JL a dit ok, mais trouver un  collaborateur autochtone. Impossible de trouver quelqu'un autochtone  pour travailler sur Carr.

- Grande exposition sur les artistes autochtones : intégration de  Norval Morrisseau par exemple et implication des commissions des  commissaires autochtones.

- Michel Snow est alors l'artiste le plus célébré au monde. Ouverture  du CP et lui est invité. Il est parmi les artistes avec jsp qui a une  expo à Pompidou en 1977.

- Snow prend en photo salle des 7 à l'ancien lieu du musée de sbx arts de Montréal. Photo peu lisibles.

- Le scénario et la scénographie : les fils de 

  Plus tard

  .

  - Snow, 

    Plus tard

     :

    - Pose la question du temps.
    - Pas de scénario sans scénographie.
    - Reconnaît le rôle des institutions canadiennes.
    - Mise en abîme.
    - Critique de ce fait la culture du paysage, comme référence naturellement québécoise.
    - Déploiement d'un accrochage de 25 photographies, semblable à celui que ces photos brouillent et rendant illisible.

- Carr est une créature du besoin national :

  - Inclusion d'un autre officiel.
  - Altérité : incarnait l'ouest, adulation de la culture autochtone, puis valorisation de genre.
  - Validation d'une autre altérité : son genre.
  - Pas possible de raconter la modernité au Canada, sans parler de Carr.

- Cet enchevêtrement du scénario et de la scénographie a contrarié beaucoup de mondes.

  - Les acteurs contrariés : sacrifier la cohérence et la signature graphique.
  - Relations les plus difficiles : avec les scénographes. Mieke Bal  était venu faire une conférence au congrès international d'HDA qui se  déroulait à Montréal. Thématique : espace.
  - Bal avait dit : musée intéressé que par la cohérence.
  - Dispositif à fabriquer de la cohérence à tout prix.
  - Idée de construire du mobilier pour chaque expo (1927, 1945).
  - Pas de signature graphique de l'expo.
  - Tous ces gestes ont une importance.
  - Discussions prises car l'expo devait circuler, et donc confrontation à des espaces différents, donc adaptabilité du mobilier.
  - Affirmer l'énonciation curatoriale.
  - Le musée ne présente pas des formes neutres : valeurs dans chacun des décors qui sont représentés.
  - Donnait à voir de l'art autochtone.
  - Défis de cette reconstruction d'expo alors qu'il y a un gros souci d'appropriation culturelle :
    - Difficultés des négociations à cause de l'utilisation artistique de  matériel anthropologique (prêt des artefacts autochtones parce que  décontextualise les approches de l'objet).
    - Nécessité d'un aval autochtone car c'est une des manières de faire  changer les musées historiques et anthropologiques avec l'appui des  "autochtones".
    - Nouvelles précautions muséographiques exigées : sans fin, par  exemple 80 ans après l'expo de 1927, valeur des œuvres de l'époque n'ont pas augmenté. Les œuvres autochtones coûtaient cher à assurer. Les  musées prêtaient mais avec des conditions muséographiques extrêmement  contraignantes. Les traiter comme des objets de valeur et les plus  précieuses de l'expo.
    - Signaler la nature de l'exposition originale (coloniale) en  résistant à la tentation de l'améliorer. (Résister à mettre de cartels  allongés par exemple sympathique) Texte qui reconnaissait la teneur  coloniale de l'expo originale de 1927, et pas envie d'édulcorer la  "violence" coloniale de l'expo.
    - Couleur x audio : comment faire entendre les voix autochtones ?  Réaliser un audioguide, voix d'un commentateur autochtone. Seulement la  possibilité de l'entendre, aucun texte. Pas emprunt d'objets qui avaient une utilisation rituelle, seulement fonctionnelle. Discours autochtone  et qui visuellement ne changeait rien à l'expo. Pour la couleur,  designer propose une palette de couleur : vert aka la forêt c'est sympa. Mais non, peinture beige, couleur du tissu de l'expo de 1927.
    - Énonciation apparaît dans l'acte curatorial : c'est plus tard.  Pourquoi tout est brouillé ? Il y a un point de vue et ce n'est pas le  neutre.

- Modèle 2 : 1945-1990

  - Murs blancs au musée des beaux-arts de Montréal.
  - Surtout, discours sur la forme et économie de tout approfondissement du sujet et contextualisation. AUCUN document d'archives encore.
  - Salle 1 : diverses explorations formelles à partir du modernisme. Toute la chrono d'EC dans cette salle.
  - Salle 2 "Résonnances affectives" donnée par JL.
  - Titre des salles fait par JL, puisque c'était son job de faire le  scénario. Cropping très proche, tête-à-tête avec "une figure  intimidente".
  - Accrochage plus réussi dans les autres lieux que dans le Musée des beaux-arts du Canada, car les salles étaient trop grandes.
  - Salle 3 : Nature et Transcendance. Dernière salle du cube blanc.  Titre qui fait référence au paysage comme spiritualité, voix extrêmement riche pour les artistes dans les années 1920 et 30. Carr était  intéressée mais résistait aussi : pas besoin de système de pensée pour  penser la nature spirituelle. Transcendance du blanc. *Fir Tree and Sky*.

- Les négociations douloureuses

  - Frontière entre les modèles 2 et 3.
  - Modèle 3 : Contextualisation de son travail.
  - Lien avec plein de phénomènes de son temps : comme l'industrie du  bois, une salle sur le tourisme culturel qui avait pour but de montrer  comment Carr s'est inspirée de cartes postales, comment elle était pas  pionnière ou unique que d'autres artistes femmes le faisaient aussi. Que les compagnies de train finançaient les artistes qui y allaient.
  - Production de l'image et de l'identité, dernière salle : "The Carr  Industry's" petit nom à l'interne. Autoportraits de l'artiste, une  peinture de son singe avec des petits habits de petites filles. Carr  était vue "comme la folle du village".
  - *Scorned as timber, beloved of the sky*. 1935.
  - Contexte d'exploitation de la peinture : Hill a proposé d'approcher un commissaire torontois indépendant, Andrew Hunter.
  - Intérêt de faire une salle sur l'industrie du bois. Une condition :  c'est moi qui aurait l'œuvre susmentionnée, et pas la salle de Nature et Transcendance. Les petits arbres sont des traces de l'exploitation.  Pour rappeler que les arbres étaient là et à quoi ressemblerait la  forêt...
  - Réalité capitaliste de cette œuvre, alors que cette œuvre a été construite comme l'œuvre la plus spirituelle de Carr.
  - Recherche dans les archives de compagnies de bois, parallèle avec  les œuvres de Carr. Les compositions sont rigoureusement les mêmes.
  - A fait une installation photo vs peinture.
  - Sentiment optimiste que la nature aurait le dernier mot.
  - Toronto : choisi une des œuvres de cette salle.
  - Vert comme paramètre signifiant.

- Salle 1 : Unnatural Landscapes.

- Salle 2 : Tourisme culturel.

  - Analyse des cartes postales utilisées par Carr, ses erreurs quand elle raconte des bêtises sur la culture autochtone.
  - Série sur l'artisanat pseudo autochtone.

- Salle 3 : Entre miroir et l'écho (?)

  - Citations sur les murs d'artistes :
    - *Mark Tobey's Emily Carr Studio* (1928) "sans moi (...) Emily Carr n'aurait jamais existé", 1957.
    - Carr l'a accueilli. Citations sur Carr.
  - Marcia Crosby, collaboratrice autochtone, comment Carr s'est rendue  dans les villages autochtones en 1928, qui étaient interdits aux blancs à l'époque.

- Dernière salle : Autre type de dispositif et de fauteuils. Autoportraits.

- Entrée de l'exposition :

  - Travail avec les communications : ont décidé pour l'affiche qu'elle  était pas assez photogénique donc on a choisi une photo de sa jeunesse  avant qu'elles soient vraiment peintre.
  - Aussi ce qu'on retrouvait à l'extérieur du musée avec une de ses peintures.
  - A réussi à mettre l'image sur le Catalogue.
  - Dans le catalogue : reconstitution du séjour.
  - Sélection d'ouvrages sur Carr, spectacles, romans etc...

- Défis de réitérations :

  - Modèle documentaire d'une expo :
    - Comment les réitérations modifient légèrement l'œuvre ?
    - Dans les différentes réitérations de Carr, celle de Toronto (seul conservateur autochtone). Il a changé :
      - Couleur mur.
      - Séparé les œuvres d'EC et autochtone dans la reconstitution de la première exposition.
    - JL a noté dans son journal, qu'il faut ajouter des conditions spécifiques pour les réitérations d'une expo qui circule.
    - Donne l'exemple de Picasso Primitif. Expo a d'abord été présentée au Quai Branly, puis a dû changer de titre à Montréal.
    - Générations futures qui sont appropriées/qui répondaient à Picasso, ajout d'une salle par Nathalie Bondil.
    - Lui aussi aurait certainement préféré avoir un contrat de respect de son itération.

- Temporalités dans l'exposition n'est pas chronologique.

- Importance du rôle de l'institution qui organisait importante :

  - Prêts exclusivement de musées canadiens.
  - Comment la culture du paysage est construite à travers le tourisme.

- Un blockbuster, c'est une exposition qui amène au musée tous les gens qui vont voir toutes les expos PAS tous les gens.

- Nom de l'exposition aurait été "plus tard".

### Silvia Kolbowski

- À la lecture des textes :
  - Faire remonter des trucs intéressants. Variété de l'art décrit.
  - Rosalyn Deutsche, comme une éthique de l'échec ou de la défaillance.
  - Modernisme nous a habitués à la narration triomphale qui ne reconnaît pas les vertus heuristiques de l'échec.
  - En quoi est-ce une éthique ?
  - Œuvre est réalisée ou triomphe l'histoire et les archives orales, reconnues comme une forme de mémoire.
  - On peut pas dire que pour la reconstitution uniquement quand il y a de l'intention : artistes.
  - Idée de la mémoire.
  - Entretien avec les artistes pas avec interprète.
  - Éthique de la plénitude : effets de présence de Gombrecht, vertus de s'intéresser pas seulement à la signification, mais à des effets de  présence. Reconnaissance qu'on y accède par les sens. Ils viennent avec  une plénitude.
  - Nos deux objets : **expérience de la présence sans plénitude.** Surtout dans les blockbusters, surcharge des œuvres parasites.
  - Surcharge des œuvres parasites dans les accrochages est écrasant.
  - Effet de présence avec Payant.
  - Expérience de la performance, comment on restitue alors que sensation que tout nous échappe ?
  - Question du spectateur : années 60, 70. Critique de Debord, beaucoup des interventions interrogent la passivité des spectateurs, la  frontière entre la scène et le public. On sent que cette frontière est  une des choses qui est en train d'être redéfinie et acceptée en tant  qu'œuvres conceptuelles.
  - Définition de l'art conceptuel : elle opère un déplacement de  l'autorité des artistes et/ou des personnes interviewées, seulement  comme des spectateur·rices.
  - Questions soulevées par rapport à son propre sujet : tisser des liens.

### À faire

- Lui revenir sur nos textes et désirs pour le deuxième bloc.
- Préparer une analyse du texte selon les questions posées.

#### Calendrier

- 13 mai : KOLBOWSKI.
- 15 mai : WARD et PAYANT.
- Semaine suivante :
  - 20 mai : Plénitude et Présence, Gombrech (Johanne doit nous l'envoyer).
  - 22 mai : DAVIS, [lien vers l'article](https://www.tandfonline.com/doi/epdf/10.1300/J082v27n01_07?needAccess=true).