---
title: "Présence et plénitude #1"
date : 2025-05-13
format:
  html:
    page-layout: article
---

#### Liste des artistes Kobolwski

- Vito Acconci
- Denis Adams
- Mac Adams
- Connie Berckley
- Dara Birnbaum
- Mel Bochner
- Hans Haacke
- [Eileen Hickey-Hulme](https://www.dailymail.co.uk/news/article-5717423/Artist-evicted-rent-stabilized-Manhattan-loft-hit-record-fine-Airbnb-rental.html)
- Mary Kelly
- Joyce Kozloff
- Louise Lawler
- Leslie Levine
- Jonas Mekas
- Allan McCollum
- Howardena Pindell
- Lucio Pozzi
- Yvonne Rainer
- Dorothea Rockburne
- Al Ruppersberg
- Carolee Schneemann
- Lawrence Weiner
- James Welling

#### Approche générale

- Frapper sur la manière générale, singularité, dans la teneur de l'entretien.
- Rapport aux dates.
- Comment organiser les questions à couvrir.
- De quoi cette œuvre serait-elle le modèle ?
- Titre de l'œuvre : aucune majuscule.
- Date de la première itération : 1999, coïncide avec une première  apothéose des archives orales, constitution de l'histoire orale à la  mode.

#### Définition de l'art conceptuel

- Commencer en regardant la question donnée par l'artiste pour l'entretien.
- "Décrivez" pas "parlez de".
- Expérience, dimensions phénoménologiques et témoignage, idée de distance.
- 1965 - 1975 : époque ==> premier cercle de réception.
- Catégorie de l'art conceptuel n'est pas définie, application rétrospective.
- Elle s'étonne qu'autant de personnes parlent de performance.
- Pas de performance à l'époque mais des actions, happenings.
- Accentuation que nous pouvons considérer, appel de la description de l'art conceptuel qui est donné.
- Idée de choc que les gens ont vécu comme un changement de paradigme.
- Nouveauté de ce qui se passait et que chacun·e interprète par rapport à son propre travail.
- Parle déjà de l'art conceptuel comme une forme de documentation.
- Registre d'un art qui pose des problèmes de documentation, mais qui se posait déjà à l'époque.
- Au final, elle répond à sa définition de l'art conceptuel avec cette œuvre.
- Aucune des bandes-son ou des films n'ont fait l'objet de montage.

#### Doxa Lanzmann

- 1985 : discussion autour du film [Shoah](https://fr.wikipedia.org/wiki/Shoah_(film)) de Lanzmann.
- Éthique de l'entretien, on ne monte pas une entrevue quand il s'agit de témoignages aussi importants, les gens peuvent parler leur langue  maternelle, et sous-titres seulement.
- Avoir le texte original primordial.
- Époque où il n'y a pas beaucoup d'archives orales, mais fixe une éthique du documentaire.
- Cependant, prendre distance de la doxa Lanzmann à cause de la  violence des sujets pour les avoir devant la caméra : il remet dans la  situation qui est celle qui a connu aux camps ou les emmenaient dans les camps.
- Manipulation, est-ce que vraiment éthique ?
- Authenticité obtenue par paramètres très contrôlés.
- Donc pas de montage, pas de son.

#### Retour à l'art conceptuel

- Quand elle présente son œuvre dans la revue *October*.
- Tension entre le fait que l'on parle d'art conceptuel, avec toute la dimension médiation, pas accessible directement, documenté par des  dessins.
- Alors que l'art conceptuel est associé à un renoncement au Faire, relatif effacement de la main de l'artiste.
- Elle ramène l'artiste représenté par sa main.
- Série des autoportraits d'artistes : dissociation de l'œil et la main.
- Elle prend la peine de souligner que le son est, elle utilise un  lecteur CD de la compagnie Bang et Olufsen dont la pub est connue, *created not made*.
- Affirmation qui pose la techno non dans un éventail de produits  fabriqués, mais créés comme un échelon au-dessus de la fabrication.
- 22 textes, un entretien.
- Ils ne peuvent pas créer de cadre.
- Cherche du référent stable : encadrement temporel.
- Commence et termine sur une date : moyen d'avoir un cadre temporel.
- Implication du public.
- Œuvre qui prenne parti.
- Description élargie, contingence, atmosphère.
- Œuvre et expérience contextualisée.
- Conscience de l'anachronisme dans l'usage de leur vocabulaire.
- Montre qu'on est pas dans une expérience objective.

#### Témoin d'une génération

- Importance générationnelle reconnue comme ayant été transformationnelle de l'art.
- Mise à mort du formalisme.
- 1999 : 2 ans après [Generations et geographies in visual art](https://www.routledge.com/Generations-and-Geographies-in-the-Visual-Arts-Feminist-Readings/Pollock/p/book/9780415141284).
- Michael Fried était venu parler de ça et Johanne, découragée, est  partie vomir, aussi parce qu'elle avait trop picolé maybe mais surtout  parce qu'elle était grande défenseure de la théorie.
- Intéressant de voir la liste de noms, et aller voir les dates de naissance.
- Expériences contextualisées : décor, atmosphère, public.

#### Fried : Art and Objecthood

- S'oppose à l'art minimal.
- Il est du formalisme, de l'école de Greenberg, modernisme : réflexion sur le medium.
- Contenu est la réflexion pas l'illustration.
- Délimitations and flatness. Ex : Stella.
- Pas de profondeur, de phénomènes matériels picturaux. Valorisaient teinture de la toile.
- Fried était un jeune étudiant, qui s'est rangé à cette doctrine-là.
- Critiques dans Art Forum :
  - Art minimal trichait au fond, qu'il ne réfléchissait pas aux paramètres de la sculpture, mais il créait une situation.
  - Sculpteur ne font ni des monuments ni des bibelots mais des œuvres à échelle humaine.
  - Ces œuvres sont des alter-egos du spectateur, et le job de  spectateur c'est de les voir en situations et d'en faire l'expérience.
  - Mais dès qu'on parle de l'expérience, on parle de l'expérience du spectateur.
  - Mais ce qui est important est dans l'œuvre = trahison de l'œuvre formel. L'instant épiphanique : presentness is grace.
  - Il pose la question de la durée.
  - Expérience : analyse d'une situation de sa place par rapport à un  objet. Pour Fried, l'art minimal c'est trop littéral. Il voyait le temps (duration).
  - Quelque chose de trop littéral et comme il voyait la duration, art  devenait une situation expérimentielle. À cause de ça, il trouvait ça  trop littéral, il parlait d'art littéral pour parler de l'art  minimaliste.
  - Il trouvait que l'art minimal, il trouvait cela théâtral, parce que  le théâtre n'a pas de spécifiques, pas de réflexion de la spécificité du medium // c'est pas vrai lol.
  - "Theatre is what lies between the arts". Mémoire de Johanne sur cette phrase.
  - Fried s'est emparé du concept de théâtralité et l'a projeté sur toutes les époques.
  - Barthes : théâtralité c'est le ... sans le texte.
  - Même démarche soustractive que l'art minimal, bisous la mise à vue.
  - Repris dans une anthologie, et tout le monde s'est mesuré à Fried :  la plupart des gens, disant qu'il était un peu bête, mais oui c'est un  ...
  - Oui, c'est un art qui s'inscrit dans la dimension expérimentative. Oui, sentiment de présence et alter-ego.
  - Lui admirait la présence, seulement un instant.
  - Beaucoup des textes parlent de la durée.

#### Débat transcendé

- Pas seulement la transcription émotionnelle, aussi du débat  transcendé. JL ne pense pas qu'en 1966 devant un happening, pas  intéressant parce que cela durait.
- Bien qu'en respectant la consigne : ne peuvent s'empêcher de donner  valeurs associées à ces expériences, associées par le débat et la  théorie du temps.
- 1976 : Lucy Lippard, The dematerialization of art. Refus de la  dimension matérielle, depuis repris comme une caractéristique de l'art  conceptuel.
- Retrait de visualité.
- Les participant·es peuvent avoir le sentiment qu'ils se remettent  dans l'état où ils ont expérimenté ça, état contaminé par les débats  théoriques des années suivantes.
- Fried, beaucoup lu dans les années 80. Tout le monde est contre mais il marque les esprits le petit.
- C'est quoi sa réception aujourd'hui ?
- On est dans un phénomène mémoriel : une rétrospection contaminée par le théorique et non l'expérience.

#### Remarques singulières

- Pas de côté nostalgique dans les textes.
- Après l'art minimal, plus de chapeau et ou de mouvement, l'art conceptuel c'est offrir une catégorie à un monde qui n'en a plus.
- "Donc, c'est devenu, l'art conceptuel est devenu non pas tant une  catégorie en soi la tentative désespérée de faire une catégorie".

#### Iconographie

- Mains.
- Mise en scène des mains : accessoires : bijoux, vernis, objets.
- Rythmique : gestuelle, JL se souvient du pouvoir hypnotique.

#### Fonction spectatorielle

- Voix 1 : alternance entre la salle et la scène. Description des *happenings* de l'époque, description simultanée de plusieurs événements.
- Allan Kaprow occupe le devant de la scène à partir de 1964.
- Should the artist become a man of the world ?
- Séparation entre le monde de l'art et le monde en général.
- Alternance, durée, singularité des artistes, encadrement temporel, alignement chronologique.

#### Le choix des œuvres

- Extrêmement anachronique. Parle d'une expo comme projet conceptuel comme c'est le cas pour le 2.
- Littérature de l'objet expo commence dans les années 1990.
- Y a-t-il des moyens de faire rentrer des discours ?
- Rétrospection.
- Texte 3 : travail sur la lumière réelle, vrai jeu de lumière () pas la lumière représentée.
- Paradigme immersif : qui appartenait à l'époque à la critique sociale.
- Rupture frontière spectateur et .....
- Guy Debord, *Happening*, finir avec la séparation des frontières et jsp quoi.
- Artaud.
- 4: instrument de mesure, côté de la description.
- 5 : performance, body art. One and one. Seul spectateur à un moment donné. Chair à chair. Relation particulière.
- Valeur n'est pas celle de l'esthétisation, mais celle de la tension.
- Sentiment d'y être. Joie d'en être. D'où cette espèce d'euphorie. Importance de la présence.
- Contentement, ne pas être exclue. Sentiment d'appartenance.
- Action painting. Mort la notion de composition.
- Happenings désireux de maintenir ce all over d'événements.
- 6: un des plus conceptuels. Idée concrétisée, concept exécuté. Collection privée.
- Beaucoup de voir l'art conceptuel.
- Vocabulaire plastique.
- Critique de la composition, Pollock.
- Niveau de lecture difficile, si on n'arrive pas le bagage historique.
- 7 : reconnaissance de la mémoire comme un système défaillant.
- On va être dans des démarches où d'entrée de jeu, on essaie de contrer la brèche de défaillance.
- Comme une expérience pourrait être enrichie ?
- All statements are true as the speakers recall them.
- Texte sur la physicalité.
- Corps à corps, relation fusionnelle, interaction auteur, medium et receveur. Esthétique de la communication.
- Juxtaposition des termes.
- 8 : Acconci. Elle parle de body art.
- Comment ça met en jeu la croyance ?
- Transformation de l'individu face aux œuvres.
- ==> Rétrospectivement, le choix de mettre l'art conceptuel comme  un type d'art comme l'occasion d'expérience affective, comme l'art l'est tout le temps.
- Dès qu'il est associé de l'affect, est susceptible de rapprocher une œuvre dont le potentiel esthétique n'était pas saisissable à la base.
- 9: Restaurant de Gordon Matta-Clark.
- ==> Enjeu de l'art conceptuel, signe la mort des étiquettes des mouvements.

#### Contribution à la fabrication du travail

- Globalement, comment cette œuvre va pouvoir contribuer à façonner le travail qu'on essaie de faire sur des objets ? Contraire de la Genèse  curatoriale.
- Réception de ces projets-là, et non à la genèse.
- Réception vraiment privilégiée : premières destinataires visées.  Désignation particulière qui réduit/ajuste l'ambition du projet.
- Esquisse une histoire : histoire lacunaire ou si c'est seulement une œuvre de mémoire qui n'a pas des matériaux susceptibles de participer à la fabrique de l'histoire.
- Soit en étant vérifié soit en étant expliqué comme quelque chose d'emblématique.
- Tension mémoire/histoire est contournée par la pratique du souvenir, pas très ambitieux mdr.

#### Semaine prochaine

- JL fait le recensement des émotions, texte par texte.
- Voir ce que nous sommes susceptibles d'en faire.
- Comment ça peut informer la démarche qu'on a autour d'un objet ?
- Regarder comment, non pas des spectateur·rices d'un art qui  s'adresse pas à tout le monde, ni les artistes parlent de leur souvenir  avec un peu de conscience qu'ils ont les outils pour en parler. Mais  ceux qui parlent en ayant, en donnant une mission de passeurs. Comment  on fait l'histoire.
- Réception, non pas dans la genèse. Mais une réception dont l'inscription historique est particulière : réception première.

#### Distinction de nos objets

- Performance dans sa démarche de muséalisation s'est éloigné beaucoup du moment fondateur de sa critique, autour de l'aura de l'artiste.
- Pas certaine que ce soit le cas pour l'exposition.
- Événement le point commun entre performance et expo.

#### 2ème bloc sur l'événement ?

- Traces : laisser des traces, et/ou être trace.
- Vérité ou imaginaire ?

#### Jeudi : Ward et Payant

- Jones, Amelia. 1997. « “Presence” in Absentia: Experiencing Performance as Documentation ». Art Journal 56 (4): 11‑18. https://doi.org/10.1080/00043249.1997.10791844.

