---
title: "Holling & Gusman - Performance"
date : 2025-06-10
format:
  html:
    page-layout: article
    
---

# 10 juin - Holling & Gusman

**Présentation Camille Gusman**

Intérêts :
* Politique de la représentation du regard
* Histoires de la performance  
* Documentation de la performance
* Critique théâtrale

Professeure adjointe à l'Université de Rome en études théâtrales et performance.

**Initiatives similaires**
Suisse : Hölling, Tate. Peu en France. Performance Sources créé par le Générateur. CNAP ouvre la question.

**Gusman**
La documentation ne vise pas seulement à reconstruire les performances passées mais constitue aussi un outil critique pour analyser la manière dont ce passé et ces récits ont été construits, façonnés par les supports médiatiques utilisés pour les enregistrer. (p.2)

La représentation de la performance engage une négociation de son identité, de ses propriétés constitutives.

Pour Hölling, agentivité de la performance en tant qu'œuvre active.

Qu'est-ce que la performance ?

**"Ça va trop vite, j'arrive pas à prendre des notes."**

Giannachi : Agencement de Deleuze et Guattari. Construit et transforme le sens que nous attribuons à la performance ainsi que sa valeur artistique et culturelle. Double indice temporel de la documentation : trace du passé et documentation pour l'avenir (Gusman).

Hölling : le care.

**Questions**
JL pense que Latour sur la partition a lancé les réflexions sur la documentation de la performance.

Multi-sensorialité ?
→ Tu parles d'une différence dans la définition de la performance entre Hölling (conservation) vs Gusman (reconstitution). Hölling...
→ Ils ont des sources similaires, est-ce que tu trouves qu'ils ont les mêmes conclusions ? → Gusman cite Hölling.
→ Care, musée, documentation citoyenne.

**Mise en scène : Parcours performatif**
Musée d'art de Joliette.
Les visiteurs ne sont plus seulement témoins mais doivent incarner la performance.
Question sur les ressentis posés au public mais pas en conservation ?

Pippin Barr, "This artist is present" 2011.
→ Petite taille de l'institution → "À vous de jouer" BEURK

Projet fugitif au MNBAQ