---
title: "Simon & Bishop, Participation"
date : 2025-06-05
format:
  html:
    page-layout: article
---

# 5 juin - Simon & Bishop, Participation

Se pose comme un manifeste, littérature critique du musée traditionnel. Mais se croise aussi avec un courant de littérature que les universitaires ont délaissé : ouvrages professionnels.

Beaucoup sur le mode interrogatif

Marketing ou conservation ? 
Faire du musée un espace...

Volonté...

Le fait qu'elle parle autant du design montre...
Intéressée par un contenu et la qualité de l'expérience.

Usage clientéliste

## Chapitre 1 :
Le musée est menacé par l'irrelevance.

Concept qu'elle investit avec [_The Art of Relevance_](https://artofrelevance.org/)

Dans musée d'histoire : 
Collection héraldique au fil des ans, à cause de la difficulté de discriminer.

Les musées ont changé depuis la loi fédérale du patrimoine qui stipule que les musées doivent soumettre les évaluations de ce qu'ils acceptent : reconnaissent la valeur de leurs collections.

Le musée ne peut pas acquérir ce qu'il a déjà.
Philosophie du collectionnement qui se dessine.

**Active collection** : définir des cercles (comme en enfer), des niveaux d'objets dans les collections en fonction de leur degré de pertinence.

4-5 niveaux décrits : un conservateur devrait avoir le sens où va chaque objet. Active collection.

Pas de pertinence pour les musées d'histoire car un objet pas pertinent peut être activé dans l'actualité.

Classement régulièrement revu. Il est permis de se défaire des objets du niveau le plus bas. On encourage l'aliénation.

Point de vue de Simone : elle voit la pertinence comme une notion que le public impose, mais selon les goûts du conservateur ou pour la cohérence de la collection.

On classe en pensant aux usages, pas en demandant au public. Qu'est-ce que je peux faire de pertinent avec ça ?

Utilisation beaucoup les termes « interaction » vu comme une chose plutôt négative. Cf. Claire Bishop

- C'est du one-on-one pour elle.

L'interaction est vue comme une relation individuelle et souvent limitée, « one shot exchange ».

Machine programmée par les cultures locales. La machine a engueulé Johanne, comme quoi elle était ignare. Lol
Mais pas réellement participatif.

L'art participatif, avant d'être socialement engagé, une grande partie qui n'est que ludique.

L'art participatif des années 90 est davantage façonné par le tournant social.

Dans l'expérience de musée, demeure extrêmement traditionnelle d'affirmer que ça commence par une expérience individuelle.

Perla dans son premier séminaire, activiste de musée, rentre dans le musée pour changer les choses. Le musée faisait entrer une communauté et ne se souciait guère de l'interaction individuelle.

Ambition de communauté, avec...

Pour les musées d'art, encore plus intéressant car le régime esthétique. Claire Bishop emprunte la définition du régime esthétique à Jacques Rancière : régime autonome d'expérience non réductible à la raison ou à la moralité.

Esthétique : inconcevable en dehors du niveau de l'expérience individuelle.

L'expérience esthétique collective existe comme l'éclipse.

**Objet social :**

- On peut le penser dans une perspective foucaldienne : cristallisation de relations.
  Le savon, rapport entre les usages avec la propreté

==> Prévalence du ME

Dans le schéma institution --> ME, pas le ME <--> ME <--> Institution

Il vise à créer des communautés de semblables : tout le monde impliqué
Comme s'il fallait offrir un dénominateur commun.

Chaque groupe est homogène.

Ouvre la question de Laura Delfino : le musée qui veut bien s'ouvrir aux publics, mais pas au débat et à la différence.
Similitude et spéculaire.

Je ne vais pas au musée pour me retrouver moi-même. À condition que ça ne fasse pas de vagues.

Attitude la procède aussi d'une forme de colonisation/condescendance. Très marqué avec les groupes traditionnellement exclus.

Souvent des échanges déculpabilisants pour le musée : forme de réduction et d'exclusion des...

Élisabeth Kaine, Traumas.Résiliences. Exposition permanente du McCord. Donner de l'agentivité au public. Délégation de l'autorité ?

**Designer le participatif :**
Si on cherche à faire du participatif dans la muséo, accès plus participatif aux œuvres pour le public. Donne l'impression qu'on y est arrivé, si on essaie de designer et de rendre ça ludique. Différent d'un artiste qui offre une participation sans demander de résultats.
Est-ce que ce ne serait pas ce besoin de contrôle ?

Insister à une participation...
Participation non réflexive ne fonctionne pas.

Claire B. : éloge de la documentation pour des formes éphémères, n'est pas très axée sur l'urgence documentaire.

Fenêtre du public est assez limitée.

Créer des profils et des cas d'usages.

Bernard Lamarche, conservateur de l'art contemporain au MNBAQ

Culture du moi : individuation transcende la catégorisation.

Médiation phatique qui concerne l'échange communicationnel.
Dans l'expo « Nous », exposition de la collection qui revendique un NOUS inclusif. Approche philosophique. Inscrit des questions en bas des murs.

Agent conversationnel s'ajoute : il pose des questions à personne lol
Le musée n'aurait pas les mêmes outils qu'en ligne.
Tout le monde pose des questions qu'il ne poserait jamais au musée.
Intérêt : place qu'il occupe dans un dispositif scénographique.

Exemple similaire ?
Tagger les émotions :

- Inscrire ces termes dans la banque de données
- Chercher des moyens de faire des expos

**Crise des scénarios :**

Différence entre la co-production et la co-création :

Jessica Minier : Mémoire de maîtrise sur la muséologie citoyenne. Belle recherche et réflexion terminologique.

Le participatif ne crée pas forcément un renouveau du musée.

Dictature des goûts du public.

Le privilège est très français hihi

Les théories crip, rendre le musée moins invalidant.
On est dans la théorie du tiers-lieu, là où les gens vont être bien. Le musée aspire à être rassembleur. Nouvelle mode à surveiller.

Désir de faire du musée un tiers-lieu, engagement social.
Attention, parce que les musées doivent rester centrés sur les œuvres.

Musée de Rouen, Sylvain Amic directeur
Carte blanche à une célébrité (Lacroix, Adler...).
Site web avec toutes les œuvres des réserves.

Collection Lambert
Classe + projet.

Projet formulé à partir d'intentions, peu de documentation.

Le musée participatif de Simone est transversal. La participation des publics est beaucoup une activité de médiation. Peu d'acquisition citoyenne.

Mais tous les musées y pensent. // Philanthropie particulière

Documentation participative ? Livre d'or, ne marche pas bien. Entretien avec le public ? Il n'y en a pas. Les rapports annuels servent. Chronologie des activités citoyennes.
Soumission de cette liste à JL, mais mélangée avec un tas d'autres affaires.

La muséo citoyenne est une modalité de la muséo participative dans ce qu'elle vise à transformer les acteurs humains, les institutions et la société où ils évoluent. Difficile de voir l'impact entre un événement de loisir et un événement transformateur ? Un événement ludique peut être transformateur : ex. chasse aux œufs au Rijks.

Mais pas d'indicateurs d'impacts ?

Les musées qui ont des initiatives auprès des « personnes plus défavorisées » : rapportent presque tous des cas singuliers de bouleversements et de transformations d'un ou deux enfants exceptionnellement.

Si on voulait documenter : voir conf JL sur la médiation phatique.
Excuses des musées pour ne pas documenter ces événements :

- On n'a pas le temps
- La plupart des musées qui font ces initiatives de cette nature-là, les font pour envoyer un message d'ouverture du musée des sociétés
  Pas le musée qui va imposer son cadre aux partenaires. Pas un protocole mais des préconisations. Seul : correspondance avec les partenaires et parfois, il y a des photos de l'événement, mais on ne peut les utiliser pour des questions de droits.
- Plus important de faire le travail que d'en garder les traces.
  Le plus compliqué, ce sont les œuvres qui sont explicitées (?), discutées par le public.

Transversalité de la question, pas seulement dans la programmation.

Au sujet du [tableau sur la co-création](http://www.museumtwo.com/publications/Participatory_Museum_chart.pdf)
**Hosted :** créé par marketing pour faire des revenus.
Mise à disposition des salles : appropriation par une logique plus communautaire. Peuvent utiliser l'institution pour leur propre but.
Contribution du marketing.

De plus en plus vers une participation intense et engagée des catégories.

Première ligne :
Quel genre d'engagement votre institution a-t-elle envers l'engagement communautaire ?

Collaborateur et contributeur existaient avant le participatif.

**Nos**
Idée de simulation, faire semblant.

Les communautés viennent reprendre des rôles qui étaient réservés aux experts à la base.
Si l'institution participait au projet, on pouvait parler de co-création.
Un des premiers ouvrages qui parlent de co-création.

La co-création signale un rapport au temps : tout est élaboré ensemble de A à Z. C'est cela qui distingue la co-création. Deux participants qui gardent une certaine autodétermination.

Comment voyez-vous la relation de l'établissement avec les participants pendant le projet ?
Les participants fournissent du contenu en se soumettant aux règles institutionnelles.

- Contribution
- Collaboratif
- Co-création
- Hosted

Catégories heuristiques intéressantes : voir mémoire de Jessica.

On peut poser qu'avant que le participatif devienne une solution à la désertion des musées, c'était une question de la pratique artistique. Pas de terminologie fixe, pas d'histoire pour ça, pas de modèle pour le penser.

Les musées ont une crédibilité sociale exemplaire :) et paradoxalement coïncide avec le lieu qui commence à théoriser le partage d'autorité.
Moins ils contrôlent le contenu, plus ils sont jugés crédibles.

Mais Claire B.
D'abord réponse remarquée, critique de l'esthétique relationnelle de Bourriaud en 2004, revue October. Première à s'en prendre à l'esthétique relationnelle.
Réfléchi modèle important basé sur l'autrice Chantal Mouffe (++), déterminante pour Laura Delfino.

(++) Défend les vertus de l'antagonisme social.

_Artificial Hells_ (2012)
Moins déterminé par CM, davantage par _Le spectateur émancipé_ de Rancière. Livre qui continue d'affirmer l'importance de maintenir des jugements esthétiques, des expériences esthétiques.

Buren, _Le décor et son double_
Dans une expo, qui est l'auteur ?
Buren accuse des conservateurs de s'ériger au rang d'artistes, concurrence. Certains mimétismes. Chambres d'amis : dialogue entre Jan Hoet, le commissaire et Buren.

Il choisit une pièce où il met ses rayures. Il va interdire la visite de la pièce. Puis va reconstruire la chambre au musée. S'inscrit dans le système de l'art et l'institution artistique. Pas une proposition de conservateur qui le sort des paramètres qu'il s'est donnés.

Participer sans complaire.

Montrer qu'entre l'art et les métiers de l'art, il y a une sorte de répondant, de rythme, de mimétisme que les artistes eux-mêmes ont théorisé.

Bouquin important sur le tournant participatif dans l'art, CB définit 3 grands moments déterminants à étudier :

- Fin avant-garde historique, 1917
- Pratique artistique jusqu'à 1968
- La chute du mur 1989 (seul qui est défini comme un moment politique)

Vague d'art participatif qui se déroule après 1989. Pour elle, contribue au néolibéralisme.

Particulièrement sur la troisième vague : ce sont des pratiques artistiques qui ont bénéficié d'un traitement différencié par rapport aux autres formes d'art : ne sont jamais soumises à un jugement esthétique mais surtout éthique. Pourtant, si c'est de l'art, devrait être soumis à un cadre esthétique.

Elle considère que se développe une scène artistique à deux étages :

Un grand public qui n'a pas à trouver un intérêt esthétique **VS** un public aguerri qui continue de s'occuper du cadre esthétique SAUF pour l'art participatif sous réserve de bonne séance.

Elle essaie de le contrer en se demandant qu'est-ce que serait une lecture esthétique de ces projets sociaux et participatifs.

Si 68 est un tournant, parce que spectateur passif (Guy Debord, _La société du spectacle_) et quelque chose qu'il faut abolir.

Années 90 qui vont commencer l'engagement social avec valorisation du participatif
Coïncide avec une grande préoccupation envers les exclusions. Le monde de l'art commence à être conscient que l'art est conçu sur des exclusions : identités nationales par ex. Époque de la mondialisation, couverture de revue avec plein de tableaux : Identity politics.

Le moment où la valorisation du participatif pour lutter contre les exclusions se sont des valeurs du monde de l'art, mais au même moment, emballement des politiques néolibérales, triomphe du capitalisme, moment de la réalité qui coïncide de la montée des marginalisations et des écarts grandissants.

Bishop pense qu'à ce moment-là, on valorise sur la scène esthétique ce qui est en train de tuer la société réelle, mais avec l'acceptation d'être relégué au champ artistique.

Ex. Emily Carr : lois appliquées avec violence pendant qu'on faisait des expositions coloniales. Comme si leur art est valorisé comme l'aura pour détourner la violence coloniale qui soudainement se déchaînait.

Pas d'argent pour donner accès à l'eau mais des millions pour redéployer les collections.

« Renaissance autochtone » vient masquer des problèmes réels.

Dans cette logique, CB souligne que le tournant participatif fait le contraire de ce qu'il prétend.
Livre vraiment intéressant : participatif.

Autodétermination. Critique de la tokenisation.
Jamais fondre les voix ensemble.

Oscillation entre figure « radicale » et figure qui l'est moins.

### Visite d'écomusée et Artexte

**Écomusée**
Accent sur la documentation des projets d'exposition.
JL nous tient au courant pour le 10 juin !

Si elle peut nous montrer la création citoyenne qui a été faite.

Pour faire l'iconothèque de la création citoyenne dans le CIECO.

**Artexte**
Façon dont il conserve leurs expos : synthétiques, ciblées.
Mais aussi, traces de performances, Festival de perf de 19?. Max Dean.


