---
title: "Méthode : l’enquête (Caillet)"
date : 2025-06-03
format:
  html:
    page-layout: article
    
---

# 3 juin - Méthode de l’enquête (Caillet)

**Présentation de Zoë. Enquête et démocratie. Le modèle pragmatiste**

**Documentation citoyenne**

**Autrice :** 
Aline Caillet 

*L'art de l'enquête. Savoirs pratiques et sciences sociales.* 
2012, Reenactment, article

- Artiste comme nouveau chercheur 
- Pratique artistique de l'enquête 

**Pragmatisme :** met l'accent sur l'expérience sur les fondements de la connaissance. 

Caillet, art diagonal. 

## Plan de la présentation

1. Introduction au modèle pragmatiste de l'enquête, en le situant dans la philosophie de Dewey 
2. Discussion des origines et des principaux acteurs de ce modèle : École de Chicago 
3. Exploration des concepts clés du modèle pragmatiste 
4. Comparaison avec d'autres formes d'enquêtes : enquête sociale et enquête journalistique documentaire

## Concepts clés

**L'enquête comme méthode interdisciplinaire :** dépasse les frontières disciplinaires, convergent vers une démarche d'investigation sans limites a priori. S'adresse aussi aux citoyen·nes. Elle est transdisciplinaire. 

Exemple : biographie de Picasso à partir des archives de police. 

L'enquête ne s'inscrit pas dans une discipline et c'est justement un outil commun et flexible pour penser le réel. Décloisonnement. 

Boltanski ne parle pas de la réalité, mais situe l'enquête en lien avec le monde. Il définit le monde, de manière très proche de l'événement : ce qui arrive ou ce qui pourrait arriver.

**Rapport de l'enquête à l'enquêteur :** 
Elle arrive à établir le lien entre la pensée pragmatiste et l'enquête.
Exploration et non pas recherche de la vérité.

Le terrain est très important pour l'École de Chicago : observation directe.

**L'enquête comme démarche exploratoire :** ouverture à l'inattendu. On ne peut pas prévoir : s'ouvrir à ne pas connaître son problème, se créer en fonction de l'enquêteur et de l'enquête. 

**Agir**
Posture de recherche : curieuse et humble 

**Savoir pratique et intelligence du réel :** 
Penser l'enquête comme un savoir pratique et non seulement comme un savoir intellectuel et théorique. 

Résoudre un problème, mais plutôt une problématique qui se façonne durant l'enquête. 

Le problème est généré par le processus de l'enquête.
Processus vivant : processus évolutif. 

**Événements :** 
- L'enquête pragmatiste ne se concentre pas sur l'événement, car l'enquête n'est pas en quête de vérité
- Cite Dewey

National Gallery de Weisman. 

---

## Notes diverses

**Musée citoyenne :** ambiance transformationnelle qui la définit par rapport aux musées participatifs. Pour la transformation : partage de projets sur une durée.  
Engagement avec une dimension temporelle, une durée.   

Comment maintenir un lien qui avait été créé ? Les liens créés sont rompus vu qu'on ne pense pas en réseaux mais en projets. Mélanie Devaux avait expliqué cela. Le musée n'abandonne pas le mode projet, parce qu'il vient avec des livrables donc évaluables.  

**Écomusée du Fier Monde :** citoyen depuis 2011. Toujours co-créé avec des citoyens. Les gens, peu importe le projet, sont dans des démarches de storytelling. Les gens veulent qu'on raconte leur histoire. Renvoie à la question citoyenne, au terme/sujet citoyen. Pas un travail par enquête.  

Lyotard dit qu'il n'y a plus de grands récits. Lui-même continue avec *Le postmoderne expliqué aux enfants* : dit que c'est encore placer le récit comme un grand signifiant. Christian Salmon et storytelling : outil de pouvoir.  

Absence de cadre prédéterminé mais pour se laisser libre. Assez confortable de se libérer mais quand on a la connaissance de son médium. Ex : les personnes viennent créer l'expo mais n'ont pas la connaissance muséologique. Se termine par un texte donc un cadre.  

**Texte à lire :** Ginzburg Carlo, sur Racine sur un paradigme de l'indice.  

Si on prend du recul : coïncide avec le moment où il y a besoin de reconnaître un statut de chercheur aux artistes. Avant faire une exposition, écrire dans le catalogue = pas de la recherche. Mais maintenant il y a des programmes qui permettent la recherche-création. Le paramètre de l'enquête permet de montrer par où un artiste est un chercheur.  

**Facteur qu'on gagne toujours à considérer :** le facteur connotatif.  

Le modèle recommandé peut être perçu comme autre chose. Enquête comme enquête policière : pour nuire à la notion d'enquête. Ishiguro : *Les vestiges du jour*. A écrit un livre : *When we were orphans*. Personnage orphelin. L'enquête apporte de l'ordre au final. Les connotations policières ont un rôle à jouer dans la méfiance du terme. La sociologie a beaucoup fait : on sait ce qu'on va trouver. En muséologie, des enquêtes pas pragmatistes.  

**Enquête :** étude par cas. Passeron et Revel.  

Rendre compte des différentes conceptions de l'exposition dans l'enquête. Annoncer définition et hypothèses concurrentielles.   

Si on pense à l'enquête par rapport à l'épiphanie : semblent être opposées. La notion d'enquête est moins passive. Sens différent. L'épiphanie est un apparaître. L'enquête est vraiment située de l'ordre de la révélation. Sentiment d'échec socio-muséologique : manque la révélation. L'enquête est une méthode mais une promesse de révélation. Révélation : quelque chose était caché, on dévoile.  

Dans le roman policier : la scène finale de dénouement. Satisfaction de la résolution.  

*Quand les attitudes deviennent formes.*  

---

**Référence :**
Morrissette, Joëlle. 2016. « What About Mozart? What About Murder? Reasoning from Cases, H.S. Becker ». Sociologie du travail 58 (2): 190‑92. https://doi.org/10.4000/sdt.1070.

## Rapport avec la conservation-restauration

**Documentation citoyenne**

Écomusée - À travailler avec Camille. 

---

## Notes de Camille

Suite des notes 
Annie Leibovitz, 

Avant de parler de la conservation-restauration, quel est son rapport ? 
Cometti, *Qu'est-ce que le pragmatisme ?* 

Conserver/Restaurer, comment l'enquête pragmatiste entre-t-elle en résonance ? 

Precious Okoyomon, 2022

De l'objet émane la problématique. Il nous apprend la problématique. 
Pour Johanne, ce type d'approche est typique pour l'histoire de l'art. 
Rapport mimétique de la performance de Dean, manière de ne pas surimposer sur l'objet des grilles prédéterminées. 

**Constat d'état de Cometti :**
Proposer de contester les propriétés des objets, elles prennent sens par leurs usages. 

Quelles enquêtes documentaires Zoë a-t-elle dû faire au cours de sa carrière ? 
Urs Fischer, Allumage de la statue de cire de 7 mètres lol. 
Apprendre par l'expérience, documentation après expérience. 

## Documentation citoyenne 

Pas seulement productrice de savoirs, aussi un acte politique.
Devient un outil démocratique.

On parle de musée dans ce texte mais :

- Soucis éthiques et politiques
- Accent sur l'écoute des voix
- Valorisation de l'expérience vécue
- Non académique, comment descendre de la tour d'ivoire
- Forme du rendu de l'enquête : quelle forme peut-elle prendre ?
- Ambition démocratique : savoirs produits avec les publics et pas seulement sur eux.

**Du participatif au transformationnel :**
Notion d'engagement qui implique que pour qu'il y ait transformation : partage de projets sur une durée.
Engagement : dimension temporelle, en tant que durée. 

Pensée en réseau, mais travail muséal pensé par projet. 
Entretenir un réseau. 

**Éco-Musée :** Musée citoyen depuis 2011
Co-création avec les citoyen·nes
Démarche de storytelling, expo veut qu'on raconte leur histoire, donc cadre prédéterminé, pas un travail par enquête. 

L'absence de cadre prédéterminé est difficile. 
Plutôt un objectif. 
Est-ce qu'on peut penser à la liberté ? Quand on est à l'aise avec l'expérience du médium, les gens qui viennent ne sont pas muséologues. Ne voient pas l'intérêt du cadre muséal. 
Le récit sert à fermer la démarche. Fin de l'exposition. 

Cadre prédéterminé pour la performance.

***Signes, traces, pistes*. Racines d'un paradigme de l'indice. Par Carlo Ginzburg**
⇒ Émergence synchronique entre l'enquête, le connaisseurship. 
Porte sur l'indice, et autre lecture du paradigme indiciel de Peirce. 

## Limites et perspectives

**Quelles sont les limites de ces modalités de travail de l'enquête pragmatique ?** 

JL : coïncide avec le moment français : besoin de reconnaître un statut de chercheur aux artistes. L'art commence à être pratiqué à l'Université comme à Paris 8. Question de la recherche-création telle qu'elle se pose en France depuis une dizaine d'années ? L'enquête pragmatiste permet de montrer par où l'artiste est un chercheur.

Un des facteurs que l'on gagne toujours à considérer : facteur connotatif. Comment les mots sont connotés dans la langue ? Enquête au sens de l'énigme policière a fait beaucoup auprès des sciences humaines pour nuire à l'enquête. 
Résolution, liée au dénouement. 
Les connotations policières de l'enquête ont un rôle dans la méfiance que peut susciter le terme. 
Du côté de la sociologie, les enquêtes socio trouvent (dans le musée notamment), on trouve ce qu'on attend depuis le début. Une forme d'étude qui va confirmer ce que l'on sait déjà. 

Mais pas l'enquête pragmatique ⇒ Caillet parle aussi de la résolution. 

**⇒ Les témoignages sont des vérités en tant que telles.** 

**Pensée par cas, études par cas.**
https://books.openedition.org/editionsehess/19901?lang=fr#anchor-resume

Comment rendre compte dans une enquête de toutes les différentes conceptions d'une expo par exemple ?
JL : demande seulement d'annoncer des hypothèses concurrentielles.

## L'enquête par rapport à la notion d'épiphanie :

**Opposée :**
- La notion d'enquête est "active" alors que l'épiphanie est passive. Forme plus active d'expérience. Mais le sens n'est pas le même : l'épiphanie est un apparaître alors que l'enquête est vraiment située d'une révélation (vraie ou pas vraie).
- Une des manières précisément, on a un sentiment devant certaines enquêtes sociologiques d'échec : la dimension de révélation est absente.

L'enquête est aussi une promesse de révélation en dehors du monde académique. Révélation = déchirure du voile. Le fait qu'on n'a pas de cadre prédéterminé, la barre est d'autant plus haute pour la révélation. Pas forcément du côté du sensible mais de l'intelligence des choses. 

*Quand les attitudes deviennent formes*

- Modèle de différent entendement d'un mot
- Modèle de reconstitution presque fétichiste

## Conserver-restaurer 

Comment ?
Distinction entre l'histoire de l'art/muséologique et conservation-restauration.
L'enquête est dans le champ lexical des contours : poreux.

Modèle interactionniste :