---
title: "L’événement sur le terrain de la performance et de l’exposition"
date : 2025-05-30
format:
  html:
    page-layout: article
---

### Notion d'événement

Nous ne nous concentrons pas sur un point de vue terminologique et sur la migration épistémologique. Aujourd'hui, nous nous concentrons sur la scène de l'art et du musée, mais cela concerne également la production culturelle et artistique en général.

Célébration du point d'interrogation dans les deux textes :

- L'événementiel est-il l'adjectif de l'événement ?
- Sentiment que l'événement et l'événementiel sont une amplification pour la communauté.
- Événemential, sur le modèle de l'événementialité. Expérience événementiale qui n'envoie pas à l'horizon de communication de l'événementiel.

L'événementiel, dans la logique des musées, pour compenser les effets du numérique. La contemplation des œuvres est moins valorisée par le grand public, principalement à cause des réseaux sociaux. Cela a à voir avec ce qu'appelle l'imagerie partagée par Gubern. Quand on entre dans une logique de buzz autour d'une image, combien de fois elle est partagée et non l'expérience de l'œuvre. Quantitatif vs non valorisation de l'expérience individuelle et qualitative face à l'œuvre.

En France, controverse autour de Fleur Pellerin, surprise de prendre des photos lors d'un vernissage alors que c'est interdit. Le musée a levé cet interdit suite à cela.

**MBAM** : Lors de l'exposition d'un verrier en 2013, le musée a acheté son arbre de vie qui sort l'été, enseigne du musée, un emblème du musée parce que ce fut un coup de cœur des guides. Dans son exposition, les publics ont été invités à prendre des photos et à les diffuser sur les réseaux.

Cette logique de l'événementiel est très présente.

**CIECO hypothèse** : Mairesse, nouvelle muséologie, musée spectaculaire. JL pense qu'au contraire, la mise à vue de l'art n'est pas à l'événementiel.

Lié à la mise à vue de l'art, pas à l'événementiel. Muséomanie dans l'architecture, effet d'attraction. Cela commence avec Beaubourg et cela ne s'arrête jamais.

**Rosalind Krauss** : Retrait de visibilité et une expérience visuelle pauvre mais qui était donnée à voir dans un lieu exceptionnel. Donner à voir le vide dans une exposition d'art minimal. Cette logique que Mairesse appelait musée spectaculaire.

**Fraser** parle de l'importance de Vienne. Vienne, naissance d'un siècle. Changement de paradigme à ce moment-là. Vienne était une exposition-ville.

Après toute une série d'expositions à Beaubourg, on sortait de la relation entre les villes pour se déplacer vers une seule ville et offrir une expérience touristique au spectateur.

Pas du tout didactique, comparé aux expositions antérieures. Reconstitution, etc.

Modèle scénographique emprunté aux grands magasins.

**Muséomanie** : Muséologie spectaculaire, titre de Mairesse. Nouveau intérêt pour la scénographie ou la mise en scène l'emporte sur... un SMS haha.

**CIECO** préfère parler de muséologie événementielle.

**2010** : Crise narrative après tous les blockbusters. On avait fait le tour des mouvements, des jumelages (Pissarro-Cézanne, etc.), de plusieurs artistes comme Manet, Vélasquez.

Déjà cette formule montrait que les musées ne savaient plus trop...

Les expositions thématiques ont commencé à être valorisées, elles permettaient de brouiller les frontières apportant le principe de choc ou de heurt, plutôt qu'harmonie. Accrochage de 2019 au MoMA est de cette nature.

**Manet** : Ritorno a Venezia - Palazzo Ducale - Italie, Venise, 2013. Un des contre-exemples de cette valorisation de la dissonance (ou insertion anachronique allotopique) : (relative dissonance) la réunion à Venise de l'Olympia de Manet et la Vénus d'Urbino de Titien. 2013.

Deux chefs-d'œuvre qui ne bougent pas, l'une à Florence, l'une à Orsay. On attendait une foule de personnes, mais il n'y a pas eu un excédent de visiteurs. La médiation a vraiment fait l'emphase sur le choc que produirait la rencontre entre ces deux œuvres. Mais trop prévisible, inscrit dans la tradition de l'histoire de l'art. Comparaison entre Titien et Manet.

Surtout une question de diplomatie culturelle entre les États.

Reconnaissance du choc, la dissonance est le choc aujourd'hui. Désir de faire événement, couverture médiatique essaie de porter le choc esthétique au niveau de l'événementiel.

Crise narrative qui fait qu'on ne sait plus regrouper les œuvres, élargissement du corpus faire d'autres disciplines comme le cinéma (cinéastes), la mode, la musique et à une moindre échelle la bande dessinée.

Réveil de la culture, et non une revitalisation de l'art.

Dans le cadre de cette grande crise, on fait des expositions thématiques : mélange d'un art et non art par exemple, expositions qui se jouent autour d'un concept.

Stratégie pas seulement communicationnelle, aussi des audaces que se permettent les musées.

En 2013, Delis se fait virer du musée de Francfort, prend la tête d'un musée d'anthropologie et a essayé de libérer les objets sous l'emprise des conservateurs, et a essayé de les activer avec un workshop, donner un sens autre et de les libérer du carcan traditionnel. Audace de conservateur.

Pas possible d'avoir une Émilie Carr pour une exposition féministe : parce que dans les hautes années du féminisme, années 1980, les conservateurs pouvaient faire valoir que c'était la réduire à une icône féminine. Conservateur pas seul en charge de sa conservation matérielle mais aussi de sa dignité. Certains conservateurs auraient dit non, parce qu'ils trouvaient ça réducteur pour Émilie Carr. Le conservateur aussi pouvait définir l'amplitude des récits où les œuvres pouvaient être inscrites.

Fonction du conservateur : pas seulement matérielle, dignité symbolique de l'objet. Notre objet est montré avec des objets de même valeur (économie et capital symbolique de l'Occident).

Exemple de Prioul : Baigneur de Cézanne vs le baigneur d'un peintre australien.

Est-ce qu'Oxford aurait prêté son Rembrandt ?

Et à partir de ce moment, on peut faire événement, créer des choses avec les collections.

Événementiel au musée est un terme plus pertinent pour décrire ce qui se passe. Très tôt, dans les années 1990, dit Fraser. Des voix se lèvent pour expliquer de réduire l'art à un statut de produit du capitalisme.

Muséologie événementielle est bien plus large en rapport. Syntaxe et contextuel. Événementiel est partout.

Se sont intéressées au terrain des collections, parce que c'est là qu'il est arrivé en dernier. Les textes de muséologie et de critique culturelle ne parlent pas des collections, disparition de l'horizon discursif. JL a grandi dans un monde où on ne parlait pas des collections. On ne parlait pas des prix ni des lieux où étaient les œuvres.

Les communications ont pris un nouveau pouvoir. Génère des revenus.

À partir des années 1970, on parle beaucoup de la prise de pouvoir des départements de l'éducation car ils font de l'argent, mais les départements des communications aussi.

Sur Émilie Carr, n'a pas gagné sur le titre en anglais. Sur le mot de l'icône.

Le musée a aussi repéré que l'on parlait : élever le vernissage en principe général de conduite. Le musée se privatise pour vos événements. Tous les musées le font.

Logique événementielle était partout sauf dans les collections. Au début, cette logique les mettait sur le côté.

Événementiel, plus on fait de la médiation et de la communication autour, moins...

En quoi le texte de Prioul...

De quoi l'événement peut-il être le nom ? Plus que la présence. Oscillation entre présence et sens (signification).

Prioul : expérience physique.

Effet de sens obligatoire pour qu'il y ait un événement.

Présence et sens indispensable pour qu'il y ait oscillation. Le dos de Johanne a lâché suite à cette épiphanie.

### Performance

Préciser le sens que le terme a pour chacune de nos recherches. On a déjà dit que l'utilisation sur le terrain des happenings est un usage non conceptualisé du terme. Est-ce un usage polysémique ?

- Pas tant du côté de la réception pour la performance.

Événement prosaïque, pas de prétention spectaculaire.

Kaprow avait une action qu'il appelait lui-même événement. Igloo en bloc de glace.

Body art américain toujours dans ce système ?

Dimension amphibologique : événement veut dire une chose et son contraire absolu. Chaque pôle a une extension : pas sûr de devoir se promener à chaque extrémité du spectre. Peut-être plus penser la question de l'oscillation ?

Processus muséologique : modification rétrospective de l'événementiel de la performance.

La performance réfléchit davantage à la conceptualisation du terme d'événement. Quand on commence à parler d'événement pour la performance ? Critique d'art ?

### Exposition

Événement discursif qui nous entraîne beaucoup du côté de la réception alors que j'ai autre chose à conserver, restaurer que l'aspect discursif.

Événement éphémère ? Éphémérité est une condition de l'expérience esthétique. Approche phénoménologique de l'objet. Approche qui prend en compte la matérialité de l'objet et le corps susceptible de produire un moment d'épiphanie peu importe l'expérience de l'objet ou sa nature. Dans une perspective phénoménologique, difficile à remettre dans une perspective documentaire.

Expliquer ce qu'on ne peut pas faire. Voir s'il y a un nom particulier pour parler de ces erreurs en conservation-restauration dans les rapports.

Dans les choses intellectuelles, comme la rédaction d'un doctorat, tentation de cacher ce qui n'a pas fonctionné. Alors que reconnaître un problème va au contraire aider. Ça cause des effets profonds dans le processus de recherche, ça freine l'écriture par questions.

- Mode interrogatif a des limites, ton de l'encyclopédique et effet de théorique.

Effet rhétorique de poser toutes les questions dans un paragraphe amenuise la force de certaines d'entre elles.

### Fraser

Historiographie de la muséologie événementielle dans le discours de la muséologie. Comment cela impacte la vision des collections, dernière à être impactée par la croissance de l'événementiel.

Au pinacle, du triomphe des collections, plus le temps de s'occuper de la conservation. D'un point de vue de la pratique.

Hybridation de la conservation et de l'exposition. La conservation est aussi un espace d'expérimentation.

L'exposition à travers la restauration est un moteur de la production de connaissances.

Ancrer des choses. Exposition/collection se cristallisent avant, dans les années 1920.

JL apprécie Damish mais fait une réserve : premier musée d'art moderne années 1920. Premières expositions fin 19e et grands coups d'éclat avec 1902 avec les primitifs. Musées avant faisaient que de la collection, accessible gratuitement. On prévient tout de suite les musées que ce sont des initiatives payantes.

Valeur d'actualité plus grande.

Muséalisation de la performance // modification rétrospective de l'événementiel de la performance. Potentiel des collections dans leur pouvoir de raconter rétrospectivement le passé que le raconter dans son actualité. p.33.

Sur la valeur d'actualité en histoire de l'art : pôle classique et baroque - 5 catégories pour juger les tableaux. Avait écrit un livre : Renaissance et baroque.

En 1920, on s'aperçoit que non, l'art ne passe pas de la Renaissance au baroque, moment weird entre les deux que l'on appelle le maniérisme. On avait vu le maniérisme avant 1920. Dans la foulée de l'expressionnisme allemand. À quel point, l'art contemporain permet de montrer des choses du passé ? Art du présent révèle des trucs dans l'art du passé. Didi-Huberman quand il parle de Pollock a permis de révéler Fra Angelico.

Gauguin, à côté c'est de la petite bière.

Contemporain ne peut pas être un temps seulement présent. C'est une co-construction de différents temps.

Chez Rivage : Qu'est-ce que le contemporain ? Agamben. Qu'est-ce qu'un dispositif ? L'ouvert.

Question que les musées d'art contemporain se posent la question entre le moderne et le contemporain au sens américain du terme. Comment on départage le moderne et le contemporain ?

Modernité milieu 19e, Foucault et d'autres ont dit que la modernité commençait début 19e.

Déplacement du paradigme de l'imitation à celui de l'expression.

Art actuel : c'est le cours impossible. Ce qui se fait au moment où on parle.

Musée d'art contemporain, ce débat sur le fait qu'il est un musée d'art moderne et contemporain.

Muséalisation de la performance // modification rétrospective de l'événementiel de la performance. Potentiel des collections dans leur pouvoir de raconter rétrospectivement le passé que le raconter dans son actualité. p.33.

Prioul parle de Dosse avec l'écrasement des temporalités.

Les collections étaient garantes de mémoire du passé. Elles sont devenues utiles pour réactualiser et lire le présent.

L'événement est-il intrinsèque à la performance ?

Acte.

**Chantal Pontbriand** : Austin, définition énoncé performatif au sens linguistique, ça fait l'événement. En prononçant cette phrase, je change la réalité. Exemple de "I do". Il faut qu'un ensemble de conditions soient réunies pour avoir un événement "réussi". Félicité.

Modifie la théorie du performatif chez Austin : deux types d'énoncés, performatif et constatif.

La table est sale : constatif.

Reviens sur ce clivage, parce qu'au fond tous les actes de langage soient performatifs car toujours un aspect sous-entendu, prendre conscience d'une nouvelle réalité.

J'y serai à 3h. Verbe fort du performatif : je promets. Promesse, le serment.

Au début des années 1980, gros débat. Surtout dans les questions de langage plus que dans les arts visuels.

La collection exposée.

Réponse à ce que JL soulignait : comment expliquer cette dédiabolisation de l'événementiel.

Tous les auteurs cités étaient contre ce musée événementiel. Comment dédiaboliser ces avis ? Le tournant événementiel a forcé les conservateurs et musées de revoir leur connaissance des collections = tournant réflexif des musées = une véritable portée critique.

En lien avec ce que Marie Fraser dit que la critique institutionnelle, en voulant le ramener dans le musée, les conservateurs ont dû modifier leurs pratiques et donc a conduit à participer au tournant réflexif des musées.

Événementiel toujours potentiel positif pour la production de connaissances.

Événementiel entre de bonnes mains peut devenir un outil ou un levier de transformation des pratiques curatoriales.

Transformation du musée, des pratiques curatoriales et même des directeurs qui "sont tombés en disgrâce".

Nathalie Bondil, avait un sens inné des nouveaux usages des collections. Ne communiquait pas beaucoup sur ses initiatives vieilles écoles.

Elle ne communiquait pas sur les initiatives qu'elle avait : vieille école. Par exemple, constat que les Montréalais n'ont d'icônes dans leur collection. Elle a entrepris une campagne d'affiches dans les écoles. Pour que les petits grandissent avec 3 images d'œuvres. Pas de contextualisation par l'histoire de l'art, mais l'actualité.

En parallèle du travail d'iconisation sur l'Otto Dix.

Stratégie événementielle : multiplication des prêts de l'œuvre de Dix.

Événementiel afin de créer du lien entre une communauté et des œuvres, en se disant que cela allait de la survie du musée. Actualisation de ses œuvres là dans le présent.

Démarche qui fonctionne, souvenir de jeunesse de Jojo. Effets positifs sur la production des connaissances, les approches des publics : création d'un sentiment d'appartenance au musée. D'une manière autre, peut aussi donner lieu : liberté de pratique, on explore différemment ?

Van Abbemuseum, archives.

Collaboration d'une œuvre de Picasso en Palestine. Picasso en Palestine. Khaled Hourani. Documentation du processus.

MF s'est aperçue que ce Picasso est presque un jumeau de celui de Tel Aviv.

Musée met en péril son œuvre la plus chère pour participer à une démarche à laquelle il adhère.

Une fois qu'on accepte de faire de l'événement, les pratiques s'élargissent, d'avoir un regard critique sur les aspects du musée, notamment celle de qui parle au musée. Qui n'est pas du tout une réponse simple.

Hans Haake dénonce l'industrie du cuivre et capitalistes du comité du Guggenheim. Le BOD a annulé l'exposition.

Pour une exposition Renoir : audioguide : point de vue d'une féministe, une anthropologue.

L'événementiel se trouve diabolisé. L'événement se trouve exalté dans la valeur qu'on lui accorde, une fois qu'on le voit comme précisément comme le modèle de G : oscillations entre effets de sens et effets de présence.

Le point d'interrogation de Prioul.

Emploi ponctuel dans un ensemble de circonstances, conjoncturel.

Exposition "Nous" au MNBAQ. Questions sur le mur. Qu'est-ce qu'ils répondent ? La réponse ne les intéresse pas. À quel moment le participatif devient... ?

Médiation phatique, qui montre que le système du musée est communicationnel. On peut poser la question pour s'assurer que ça marche. Testing, testing devant un micro.

[Schéma de Jakobson](https://fr.wikipedia.org/wiki/Schéma_de_Jakobson)

JL pense que la médiation devient phatique et que l'interrogatif est un contact phatique uniquement, seulement vérifier que le canal musée-public est ouvert. Prépondérance des interrogations un peu partout dont le musée, idem pour les émissions télé.

À partir de cette fonction de...

Caillet, Aline. 2019. L’art de l’enquête : savoirs pratiques et sciences sociales. Art, esthétique, philosophie, n. 6. Milan, Paris : Éditions Mimésis.

### Mise à jour du plan de cours

**Semaine prochaine :**

**3 juin :**
- Présentation du texte sur l'enquête.
- Boltanski ?

**5 juin :**
- BLOC Participation.
- Parcourir "Le musée participatif" de Nina Simon [en ligne].
- Johanne va montrer la tension de la participation de Claire Bishop.
- Notion de participation dans la production artistique.
- #documentation.
- Rien, presque rien en termes de documentation dans la participation.

**10 juin :**
- Présentation Camille : Holling et Gusman.
- Cas d'étude.

**12 juin :** (à confirmer)
- Visite de l'écomusée (co-construction des expositions).
- Encourage la création citoyenne, mais musée sous-doté.
- Musée qui a une grande reconnaissance en France.
- Et Art-Texte pour reprendre la question de la documentation.

**17 juin :**
- Présentation de Display.
- Bilan notionnel du cours.
- Cours instrumentalisé de chacune.

**23 juin :**
- Remise du journal de séminaire.