---
title: "Plan de cours"
date: 2025-04-01
tags: [muséologie citoyenne]
description: "Co-construction du plan de cours"
---

## INTRO

6 mai : Co-construction 
08 mai : L’œuvre modèle : essai de genèse curatoriale

## BLOC 1 : Présence/Absence

13 mai : an inadequate history of conceptual art : histoire orale, documentation, lacunes
KOLBOWSKI  
15 mai: La perte : notion constitutive de l’histoire de l’art (et de l’art?). Notes sur la performance
WARD et PAYANT  
20 mai : La production de présence de Gümbrecht. Présence vs signification.  
22 mai : Épiphanies et présentification : le passage par l’éphémère. Winckelmann et Dibutades.

## BLOC 2 : Évènement

27 mai : L’événement : évolution sémantique et migration épistémologique (Dosse)  
29 mai : L’événement sur le terrain de la performance et de l’exposition (Fraser –
Prioul)

## BLOC 3 : Enquête

3 juin : Méthode : l’enquête. Présentation de la lecture de Zoë Renaudie. Aline Caillet.  
5 juin : Participation (Simon et Bishop). La participation et la documentation.

## BLOC 4 : Collaboratif

10 juin : Présentation de textes de Holling et Gusman par Camille Delattre  
12 juin : Muséologie et documentation citoyenne

## BILAN

17 juin : La présentation de Display par Zoë Renaudie. Bilan et journal de séminaire